### ISSUE TITLE
Support is-up modifier for <Dropdown />

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#107]
Documentation for the modifier: https://bulma.io/documentation/components/dropdown/#dropup  
`<Dropdown />` could take a new prop `isUp` or `up` for the modifier.

**Comment by kennedybaird** [comment]
also is-right would make sense

**Comment by MrCreeper1008** [comment]
Actually there's a `align` prop that accepts `right` as the value. But it doesn't seem to accept `up` as an acceptable value, so I'll just need to support `up` alignment; a new prop is not needed.  
@couds does the `align` prop support `up`? If not I'll make a PR for it.

**Comment by MrCreeper1008** [comment]
`right` and `up` should be separate props since they are not mutually exclusive.
