### ISSUE TITLE
Rounded Images

### ISSUE THREAD

**Issue by brachetti** [couds/react-bulma-components#113]
Hey,

As per https://bulma.io/documentation/elements/image/#rounded-images I would like to request a such a property on the `<Image />` react component.

Currently using `is-rounded` on the `Image` will not yield desired result, as the class needs to be applied to the wrapped `<img>`.

Cheers 🍺

**Comment by MrCreeper1008** [comment]
Thanks for the suggestion. I will submit a PR for it in my free time :)

**Comment by ytm127** [comment]
is-rounded on <Image/> still not working...?

**Comment by MrCreeper1008** [comment]
Care to show your code here?

**Comment by ytm127** [comment]
`<Image is-rounded src={process.env.PUBLIC_URL + '/profile.jpg'} />`

**Comment by ytm127** [comment]
Thanks for your quick response!

**Comment by MrCreeper1008** [comment]
First, the prop name is `rounded`, not `is-rounded`. Second, prop names with "-" are invalid in react, so your ide should've been able to catch that error. Do get back to me if it works or not though. Thanks!

**Comment by ytm127** [comment]
`<Image rounded src={process.env.PUBLIC_URL + '/profile.jpg'} />`

I think this is the correct way? Any idea if it's still not working? First day using react-bulma-components. It's awesome

**Comment by MrCreeper1008** [comment]
Yes, this is the correct way.

**Comment by ytm127** [comment]
Mmm interesting, it's not working for me. i'll dig in some more. Thanks for your help sirrr

**Comment by dmcshehan** [comment]
`rounded` isn't working for me either.

**Comment by MrCreeper1008** [comment]
Interesting. I'll take a look. Thanks for reporting!
