### ISSUE TITLE
Remove inlined css for Icon (prefer FontAwesome)

### ISSUE THREAD

**Issue by dfee** [couds/react-bulma-components#116]
The [current approach]((https://github.com/couds/react-bulma-components/blob/master/src/components/icon/icon.sass)) isn't a preferred (or good, or modern) approach. I noticed there was another issue related to the use of FontAwesome icons, and I think requiring a child to render should be the preferred way.

I ended up getting it to work like so:
```typescript
<Icon align="right">
  <FontAwesomeIcon icon={field.icon} />
</Icon>
 ```

Of course, someone else might want to use a different sort of child, so I'd be fine not requiring FontAwesome as a peer dep. either – but having it in the README that this solution seems like a good choice.

**Comment by couds** [comment]
Hi @dfee 

Currently the children approach its the correct one, the css for the icons its need it for some of react-bulma-components (like dropdown and InputFile).

But yes we should update the Docs to explain how to correctly use each component (but currently I have my hand full)

**Comment by couds** [comment]
Right now the Icon css its needed because there are some component that use icons, but maybe we can move that css to the components that need the icons (or instead of using a font for the icons use directly the svg markup)

**Comment by couds** [comment]
For now I will kept the inline don't. Closing this
