### ISSUE TITLE
Update storybook

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#117]
Current storybook does not include Button Group section, but it is coded into `button.story.js`

**Comment by MrCreeper1008** [comment]
Many new storybook codes are added but they are not in the public storybook yet.

**Comment by MrCreeper1008** [comment]
@couds will the content of storybook be updated in V3? Thanks.

**Comment by couds** [comment]
Yes I will update it when I release v3 as the stable version

**Comment by MrCreeper1008** [comment]
Good to know. Thank you!

**Comment by MrCreeper1008** [comment]
Fuller support of the Bulma framework basically. @couds can you give a list of changes that is coming in V3?

**Comment by MrCreeper1008** [comment]
@uptonking by view library you mean CSS framework right?

**Comment by uptonking** [comment]
> @uptonking by view library you mean CSS framework right?

yes. but this library has advantages over bulma. I don’t need to implement tabs in js

**Comment by MrCreeper1008** [comment]
@couds

**Comment by MrCreeper1008** [comment]
Sorry, accidentally closed the issue.

**Comment by couds** [comment]
Tookme long but I'm finally releasing V3 as latest stable version. Also the storybook its now updated
