### ISSUE TITLE
Are there any real life non-story book examples?

### ISSUE THREAD

**Issue by bluengreen** [couds/react-bulma-components#120]
I can't seem to get any Navbar example to work with with the burger menu. Is there any kind of clear real life example that's not wrapped in story book? Even the story book doesn't have a working burger menu. 

```
class Nav extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
       open: false
     }
  }

  onClick = () => {
    this.setState({
      open: !this.state.open
    });
  }

  render() {
    return (
      <Navbar>
        <Navbar.Brand>
          <Navbar.Item renderAs="a" href="#">
            <img
              src="https://bulma.io/images/bulma-logo.png"
              alt="Bulma: a modern CSS framework based on Flexbox"
              width="112"
              height="28"
            />
          </Navbar.Item>
          <Navbar.Burger active={this.state.open} onClick={this.onClick} />
        </Navbar.Brand>
        <Navbar.Menu active="open">
          <Navbar.Container>
            <Navbar.Item href="#">Second</Navbar.Item>
          </Navbar.Container>
          <Navbar.Container position="end">
            <Navbar.Item href="#">At the end</Navbar.Item>
          </Navbar.Container>
        </Navbar.Menu>
      </Navbar>
    )
  }
}

export default Nav
```

With the above code I get 
```
node_modules/react-error-overlay/lib/index.js:2172 Warning: Received `false` for a non-boolean attribute `active`.
```

**Comment by MrCreeper1008** [comment]
@bluengreen
Here: `  <Navbar.Menu active="open">`  
you passed in the string `"open"` to the prop active instead of a boolean. You should pass `this.state.open`, not `"open"`.

**Comment by MrCreeper1008** [comment]
@bluengreen Sorry I misread the error message. Can you try removing the prop `active` in `<NavBar.Menu>` and see if it works?

**Comment by couds** [comment]
Hi @bluengreen.

On the storybook you should use the knob tab to open/close the navbar. 

On the example code above you should pass the open state to the `Navbar` instead of the `Burguer`.

I hope this solve your issue.

**Comment by MrCreeper1008** [comment]
@couds I think the code for Navbar in storybook is a bit weird because `Navbar.Menu` does not seem to accept the `active` prop yet it is present in the example code. Is it intended or is it an error?

**Comment by couds** [comment]
That's an error. In V1 the menú accepted the prop but in v2 it use React.Context. 

We should remove the prop on storybook for the menu

**Comment by MrCreeper1008** [comment]
Related issue #117? Current prod storybook is old and is several commits behind.
