### ISSUE TITLE
Using the Bulma sass in other .scss files in CRA

### ISSUE THREAD

**Issue by weyert** [couds/react-bulma-components#121]
I was wondering how I could leverage the Bulma sass such as the extra defined colours in other .scss files. Currently, all the variables are undefined in for example my App.scss. 

What's the best way or approach to do this?

**Comment by weyert** [comment]
Anyone got a way to support this? I am getting the feeling that every App.scss is self-contained

**Comment by couds** [comment]
If you are overriding the Bulma Variables using the advance configuration (V3) you need to import your `_variables.sass` file. and you will be able to use the sass variables.
