### ISSUE TITLE
InputFile component gives prop warnings.

### ISSUE THREAD

**Issue by emregocer** [couds/react-bulma-components#125]
It gives React does not recognize the '...' prop on a DOM element warnings.
Here is a create-react-app sandbox, just rendering the InputFile as is.

https://codesandbox.io/s/zk8k58pq33

**Comment by MrCreeper1008** [comment]
Rendering `<inputFile />` without any third-party libraries like `styled-components` wrapping around it gives the DOM element warning nonetheless, which imo isn't an expected behavior.
