### ISSUE TITLE
Custom label for <Dropdown />

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#126]
Would be great if `<Dropdown />` supports custom label!  
`<Dropdown label="some custom label" />`

**Comment by couds** [comment]
Hi @MrCreeper1008 I dont know if that is what you mean. but I just fix a bug that cause to the first element no beign selected if no item was (cb3d3d9).

**Comment by goranefbl** [comment]
@MrCreeper1008  Can you link to bulma docs where it shows this example?

**Comment by MrCreeper1008** [comment]
Doc: https://bulma.io/documentation/components/dropdown/  
Check the code in the first section; the dropdown button has a label of "Dropdown Button".

**Comment by MrCreeper1008** [comment]
I will work on this issue since it has been quiet for quite a while now.

**Comment by couds** [comment]
If you will, please make the label optional and if not present use the currently selected value (or the first element if do no have any value)

Thanks!

**Comment by MrCreeper1008** [comment]
Will do. Thanks!
