### ISSUE TITLE
How to properly override variables scss files CRA 2?

### ISSUE THREAD

**Issue by kkomaz** [couds/react-bulma-components#130]
## Issue
I feel as though I'm doing many variations of this setup but cant seem to make it work...

```
// main.scss

// Any Bulma variables I want to override go here...
$family-sans-serif: 'Overpass', sans-serif;
@import '~react-bulma-components/dist/react-bulma-components.min.css';
$primary: #0000FF;
```

In my js code

```
<Button color="primary">Please be #0000FF</Button>
```

Shouldn't the primary color change based on the configs above?   I haven't created a variables file based on the instructions **Override Bulma variables in Create React App**

## Dependencies
```
  "dependencies": {
    "lodash": "^4.17.11",
    "node-sass": "^4.10.0",
    "react": "^16.6.3",
    "react-bulma-components": "^3.0.1-2",
    "react-dom": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1"
  },
```

**Comment by couds** [comment]
Hi @kkomaz 

To override the Bulma variables you need to use the sass files (the css its already compiled so you won't be able to use variables at all)

To override the Bulma variables please follow the instructions [Here](https://github.com/couds/react-bulma-components/tree/master#override-bulma-variables-in-create-react-app)

Thanks

**Comment by kkomaz** [comment]
Thank you for the quick response!

I still cant seem to integrate the change.

```
// Any Bulma variables I want to override go here...
$family-sans-serif: 'Overpass', sans-serif;
@import '~react-bulma-components/src/index';
$primary: blue;
```

I moved the `$primary` before and after the import but doesn't want to change the primary color to blue.

```js
// App.js

import Button from 'react-bulma-components/lib/components/button'

<Button color="primary">
  Test should be blue
</Button>
```

Test Repo:
https://github.com/kkomaz/debut/tree/color-change-test

<img width="542" alt="screenshot of google chrome 12-21-18 1-17-54 pm" src="https://user-images.githubusercontent.com/8473884/50357125-d4e03080-0522-11e9-97dc-f83f692df119.png">

**Comment by kkomaz** [comment]
Hey @couds 

I updated to version `3.0.1-3`.  One thing of note is I had to change the react-bulma-components node_modules utils file like this to get it working

```
...
@import "../../_variables.sass"
...
```

Also I still can't seem to get it working.. I created a simplified CRA with the changes you recommended + docs.

## Advanced Configuration Setup

```
import React, { Component } from 'react';
import Button from 'react-bulma-components/lib/components/button';
import './App.sass';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Button color="primary">
          Primary color
        </Button>
      </div>
    );
  }
}

export default App;
```

## Variables file setup under ./src
```
// _variables.sass
$primary: #c3c3c3;
```

## package update
```
  "scripts": {
    "start": "NODE_PATH=./src react-scripts start",
    "build": "NODE_PATH=./src react-scripts build",
    "test": "NODE_PATH=./src react-scripts test",
    ....
}

Image:
<img width="332" alt="screenshot of google chrome 12-25-18 1-00-00 pm" src="https://user-images.githubusercontent.com/8473884/50425480-04ee4300-0845-11e9-8963-da385a73eae2.png">

Repo:
https://github.com/kkomaz/bulma-test

Thanks for the help!

**Comment by couds** [comment]
Hi @kkomaz 

Weird I just downloaded your repo and seem to be working

which version of npm/node are you using? I just tested inside a Docker just to be sure that was not something on my environment and also works

![image](https://user-images.githubusercontent.com/2903371/50453065-647c4980-093e-11e9-80e0-14d89310769a.png)

Try using Docker to check if mayve something in your environment its preventing this to work

Create a Dockerfile in the root of the project with:

```dockerfile
FROM node:10
WORKDIR /code
ADD package.json package.json
RUN npm i
ADD src src
ADD public public
EXPOSE 3000
CMD ["npm", "start"]
```

in the command line run `docker build --tag rbc-test` to build the image, and `docker run --rm -p 3000:3000 -v $(pwd)/src:/code/src rbc-test` to start the server.

Let me know if this works

**Comment by kkomaz** [comment]
Thank you @couds.  Your suspicion of node versioning is correct!

To recap:
## Not Working:
npm: **6.1.0**
node:**v8.12.0**

## Working:
npm: **6.1.1**
node: **v9.6.1**

Not exactly sure if its all versions of 8.xx or this one specifically but the update of node definitely got it working.

![screenshot of google chrome 12-26-18 2-15-04 pm](https://user-images.githubusercontent.com/8473884/50454929-a5f9fe00-0918-11e9-9134-541771cd7b05.png)

**Comment by allmyloving** [comment]
Hi @couds, I'm working on Windows machine, so in package.json I've changed `NODE_PATH=./src react-scripts start` to `set NODE_PATH=./src && react-scripts start`, but I'm getting an error that _variables.sass cannot be found. Do you happen to know what might be the problem?
