### ISSUE TITLE
Use relative paths instead of fancy Webpack crocodiles?

### ISSUE THREAD

**Issue by tunnckoCore** [couds/react-bulma-components#131]
Just started new plain React on the CodeSandbox and it fails with

```
Error: Could not find /node_modules/_variables.sass
        on line 3 of node_modules/react-bulma-components/lib/components/utils.sass
>> @import "~_variables.sass";
   --------^
```

**Comment by couds** [comment]
Hi @tunnckoCore, 

We use this "fancy" import to be able to override the bulma variables.

If you want to use out of the box  (without any alias webpack configuration) import from the main export. and include the css file `react-bulma-components/dist/react-bulma-components.min.css`

```
import { Box } from 'react-bulma-components';
```
Thanks

**Comment by tunnckoCore** [comment]
The thing is that it's "not recommended", and not only that but it will not tree shake. But yea for playing and prototyping it would work.

**Comment by couds** [comment]
Hi @tunnckoCore 

I just release the version 3.0.1-3 (you can install it using the `next` tag `npm i -S react-bulma-components@next` in this version now its a lot easier to use the "Recommended" way.
