### ISSUE TITLE
Columns Size(ing) issues 

### ISSUE THREAD

**Issue by kkomaz** [couds/react-bulma-components#133]
## Version
`"react-bulma-components": "^3.0.1-3"`

## Question
After upgrading to 3.0.1-3 I noticed an odd issue where my columns were being overflowed based on a 12 column system.

The image of the story book is shown like this

<img width="1180" alt="screenshot of screenfloat 12-27-18 12-49-40 pm" src="https://user-images.githubusercontent.com/8473884/50489487-e4092780-09d5-11e9-99a0-ac3a0b33a2e7.png">

With the code set as

```
      <Columns>
        <Columns.Column size={1}>
          <p className="bd-notification is-success">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-info">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-warning">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-danger">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-white">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-light">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-dark">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-black">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-dark">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-light">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-white">size-1</p>
        </Columns.Column>
        <Columns.Column size={1}>
          <p className="bd-notification is-danger">size-1</p>
        </Columns.Column>
      </Columns>
```

I copied and pasted the code into my CRA app and it seem like the columns can only fit 10 instead of the intended 12.  The only work around I have around for this right now is making the top level `Columns` gapless.  Is there something I'm missing in the configuration?

<img width="1440" alt="screenshot of google chrome 12-27-18 12-51-00 pm" src="https://user-images.githubusercontent.com/8473884/50489520-131f9900-09d6-11e9-9ac8-18763d3c80cf.png">

Repo: https://github.com/kkomaz/bulma-test

**Comment by couds** [comment]
Hi @kkomaz 

Seem that accidentally I remove one step of the configuration.

you need to import `react-bulma-components/src/index.sass` on your main sass/scss file to add the generic css that bulma needs

For example in your App.sass

```sass
@import "~react-bulma-components/src/index.sass"
``` 

Please note that this file should only be imported on your entrypoint sass and not in the `_variables.sass` that is because this file actually create css rule and if you put it on the variables file the rules will be duplicated.

I will update the docs asap.

Hope this help

**Comment by kkomaz** [comment]
@couds 

Sorry for the late response.  This did the fix!  Thank you.
