### ISSUE TITLE
Box radiusless option is not working

### ISSUE THREAD

**Issue by niwatolli3** [couds/react-bulma-components#139]
The following code (1) outputs (2), but `is-radiusless` css style is not applied.

(1) input
```javascript
<Box radiusless>
a
</Box>
```
(2) output
```javascript
<div class="box is-radiusless">
a
</div>
```

**Comment by couds** [comment]
Hi @niwatolli3  can you share the configuration you are using (library version, how are you importing the components) I can't reproduce the issue.

Please ensure you are adding the file  `react-bulma-components/src/index.sass` that is the one that include the generic bulma classes. (I just updated the readme just in case)

**Comment by couds** [comment]
Clossing this due inactivity
