### ISSUE TITLE
Labeling issues

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#141]
As this library grows, number of issues will inevitably rise, so it makes sense to start labeling issues to better organize and manage them, like 'suggestion', 'needs more info', 'next release', 'serious', etc.

**Comment by MrCreeper1008** [comment]
@couds how do you think?

**Comment by MrCreeper1008** [comment]
Oops, accidentally closed the issue :p

**Comment by HJerem** [comment]
@MrCreeper1008 I agree, this is needed.
