### ISSUE TITLE
Reduce Noise of ForwardRef components

### ISSUE THREAD

**Issue by couds** [couds/react-bulma-components#142]
With the addition of the ForwardRef to all components now the React tree its quite difficult to follow with wuite a lot "ForwardRef Component" 
![image](https://user-images.githubusercontent.com/2903371/51238080-4b334f80-1976-11e9-91cf-50014c12a6dc.png)

Solution: Expose 2 components one with Ref and one without, so the developer can import the Component with Ref if necessary.

**Comment by MrCreeper1008** [comment]
How would you export both of them? In separate folders like `react-bulma-components/with-ref`?

**Comment by jchapple** [comment]
> How would you export both of them? In separate folders like `react-bulma-components/with-ref`?

I guess multiple exports, with import destructuring would be best, e.g.

```javascript
import { Component, ComponentWithRef } from 'react-bulma-components/lib/components/SomeComponent'; 
```

**Comment by couds** [comment]
I have two approach in mind:

1. Default export without ref and a named export with the componentWithRef 
```jsx
import Button, { ButtonRef ] from 'react-bulma-components/lib/.....'
```
The problem with this approach its in how to expose it when importing directly from the root component `import { Bulma } from 'react-bulma-components`

2. Create a new static prop on each component `withRef` that will be the component with the ref

```jsx
import Button from `react-bulma-components/lib/....`

export default () => (
  <div>
    <Button>Button without ref<Button>
    <Button.withRef>Button with ref<Button.withRef>
  </div>
)
```

Probably I will choose the option 2. but I'm still thinking about it.

**Comment by MrCreeper1008** [comment]
Option 2 looks better, but I wonder if there is a more elegant way to do it, like dynamic ref forwarding (export component with ref forwarding only when `ref` prop is defined. I'll dive deeper into it.

**Comment by MrCreeper1008** [comment]
Found this! https://reactjs.org/docs/forwarding-refs.html#displaying-a-custom-name-in-devtools  
Apparently we can change the display name of components with ref forwarding support in dev tools. We can dynamically change the display name such that:
1. it will be the name of the component if no ref is passed;
2. it will be `ForwardRef${componentName}` if one is passed.  
Much more elegant that exporting duplicate components with and without ref forwarding support imo. @couds thoughts?

**Comment by couds** [comment]
I think we should add the displayName But exposing both components. because if when not using the ref (that should be most of the cases) the react tree its overcomplicated for nothing.

you will end with something like

```
<ForwardRefBox>
  <Box>
    <ForwardRefButton>
      <Button>Normal button</Button>
    </ForwardRefButton>
  </Box>
</ForwardRefBox>
```

instead of 
```
<Box>
  <Button>Normal button</Button>
</Box>
```

**Comment by MrCreeper1008** [comment]
Seems like it is the only way to do it then. It isn't quite elegant, but React does not recommend dynamic ref forwarding, so we are stuck with it. :/

**Comment by MrCreeper1008** [comment]
@couds I will work on this issue, but I need to submit the PR at least a week after because i need to deal with those disgusting exams.

**Comment by MrCreeper1008** [comment]
@couds After doing some research, I think it is not feasible to export two different components: one with forwardRef support and one without. React doc specifically specifies that conditionally applying forwardRef is not recommended as it may cause unexpected behaviors. However it is almost impossible to export said components without either conditionally applying forwardRef or duplicating component logics with one exporting forwardRef HOC and one without.

**Comment by couds** [comment]
Hi @MrCreeper1008 Thanks for your research, I was thinking on something like this

```

const Button = (props, ref) => {
  const refProp = ref ? { ref } : {};

  return (<Element {...ref} ...>);
};

// This part I'm not sure if exporting as a static prop or as a named export
Button.withRef = React.forwardRef(Button);

export default Button;
```

Note: I didn't test this its just an idea, if you have time can you give it a try? (Right now I have my hand full u.u)

Thanks Again

**Comment by MrCreeper1008** [comment]
Hi @couds the ref arg will not be defined even when it is passed as a prop because we are not using React.forwardRef to receive the ref.  

**This will work:**
```
const Button = React.forwardRef((props, ref) => { ...
...
<Button ref={ref} /> // ref will be passed
```  

**This will NOT work**
```
const Button = (props, ref) => { ...
...
<Button ref={ref} /> // ref will NOT be passed
```  

I think the only way to reduce noise is to use the good old callback ref instead.

**Comment by MrCreeper1008** [comment]
If we use callback ref then passing ref to the underlying DOM element will be trivial, since we can basically treat it as if we are passing onClick callback to children.

**Comment by couds** [comment]
Hi all, At the end I added a new prop domRef that will accept a Ref created with `React.createRef` this prop will be pass down to the dom element.  =)
