### ISSUE TITLE
Warning: React does not recognize the `renderAs` prop on a DOM element.

### ISSUE THREAD

**Issue by iamronsuez** [couds/react-bulma-components#144]
I'm trying this library , so far provides excellent abstractions for bulma.

When I was implementing the Media `Media.Item`Component I got an error for the prop `renderAs`, i think the library is not deleting that prop for the underline html render element so i'm getting this error at the console.

![captura de pantalla 2019-01-21 a la s 15 32 09](https://user-images.githubusercontent.com/28957938/51492913-300b7a00-1d92-11e9-8e13-afb902814c4a.png)

**Comment by MrCreeper1008** [comment]
This might help you: https://github.com/couds/react-bulma-components/issues/89
