### ISSUE TITLE
No TypeScript support when using Advanced configuration

### ISSUE THREAD

**Issue by patoncrispy** [couds/react-bulma-components#145]
Works with TS:
`import {Heading} from 'react-bulma-components';`

Doesn't work with TS:
`import Heading from 'react-bulma-components/lib/components/heading';`

Have I missed something simple? Only just started using the library so apologies if I missed something in the docs.

**Comment by couds** [comment]
Hi @patoncrispy Sorry but right now I don't know a way to add the TS support for the advanced configuration.

**Comment by MrCreeper1008** [comment]
Adding an `index.d.ts` for every export should fix this right?

**Comment by Calinou** [comment]
With this `App.tsx` file:

```typescript
import React from 'react';
import { Button, Container, Section } from 'react-bulma-components';
import './App.sass';

function App() {
  return (
    <Section>
      <Container>
        <Button color="danger">Click me</Button>
      </Container>
    </Section>
  );
}

export default App;
```

I get the following error:

```
TypeScript error in (…)/src/App.tsx(7,6):
JSX element type 'Section' does not have any construct or call signatures.  TS2604
```

Here are the relevant sections from my `package.json`:

```json
{
  …
  "dependencies": {
    "@types/jest": "^24.0.11",
    "@types/node": "^11.13.7",
    "@types/react": "^16.8.14",
    "@types/react-dom": "^16.8.4",
    "node-sass": "^4.11.0",
    "react": "^16.8.6",
    "react-bulma-components": "^3.0.1-4",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.0",
    "typescript": "^3.4.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  …
}

```

Any idea why this is happening?

**Comment by couds** [comment]
Currently there is an issue in the 3.0.1-4 version, check https://github.com/couds/react-bulma-components/issues/165

**Comment by couds** [comment]
We are dropping the advanced configuration in favor to simplify all the process, then this will not happen anymore.

**Comment by couds** [comment]
Advanced confituration its beign removed on v4, v3 will not support TS definitions for advence configuration
