### ISSUE TITLE
Error: forwardRef is not a function

### ISSUE THREAD

**Issue by epatters** [couds/react-bulma-components#146]
When using the current beta of react-bulma-components v3, I get an error that `forwardRef is not a function`, coming from [element.js](https://github.com/couds/react-bulma-components/blob/a7916467a288578917d960b7970c1e42783e40e7/src/components/element/element.js#L6).

I'm using v3 because I need the TypeScript definitions. Besides TypeScript 3.2, I'm using React 16.7 and React Router 4.3. Unfortunately, I do not have a minimal example at the moment, as I was trying to port a preexisting app from Bootstrap to Bulma.

**Comment by epatters** [comment]
Here is the traceback:

```
element.js:6 Uncaught TypeError: i.a.forwardRef is not a function
    at Module.<anonymous> (element.js:6)
    at r (bootstrap:19)
    at bootstrap:83
    at Object.<anonymous> (universalModuleDefinition:11)
    at r (bootstrap:19)
    at Object.<anonymous> (index.tsx:5)
    at r (bootstrap:19)
    at Object.<anonymous> (hoist-non-react-statics.cjs.js:65)
    at r (bootstrap:19)
    at bootstrap:83
```

**Comment by epatters** [comment]
After upgrading `react-router` to the latest beta (`v4.4.0-beta.6`) and forcing `hoist-non-react-statics` to v3, which is supposed to be compatible with `forwardRef`, the above error goes away but I get another similar one:

```
element.js:6 Uncaught TypeError: a.a.forwardRef is not a function
    at Module.<anonymous> (element.js:6)
    at t (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    at universalModuleDefinition:3
    at Object../node_modules/react-bulma-components/dist/index.js (universalModuleDefinition:1)
    at __webpack_require__ (bootstrap:19)
    at Object../src/index.tsx (index.tsx:5)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (bundle.js:55346)
```

I am declaring myself stumped. Any advice would be appreciated.

**Comment by couds** [comment]
Hi @epatters 

To me seems that the react version loaded its not the correct one, can you post your package.json/package-lock.json?

**Comment by epatters** [comment]
Thanks, I've attached my `package.json` and `yarn.lock`.

[package.zip](https://github.com/couds/react-bulma-components/files/2804638/package.zip)

**Comment by epatters** [comment]
I figured out the problem. The version of React included from a CDN in my `index.html` did not match the version of React in my `package.json`. I had upgraded the latter, but forgotten to update the former. That will teach me a lesson about having dependencies specified in two places. Sigh.

Sorry for the noise.
