### ISSUE TITLE
Rendered UI is not the same as with plain html

### ISSUE THREAD

**Issue by jahirfiquitiva** [couds/react-bulma-components#148]
Hello

I just started using these components but I am seeing a difference between the UI rendered by React and the one from plain/vanilla html

I wonder if I am doing something wrong, or if this is an issue with the components library.

Thanks in advance!

#### With React rendering

![captura de pantalla 2019-02-14 a la s 8 13 12 p m](https://user-images.githubusercontent.com/10360816/52828021-1d384c80-3095-11e9-9f79-e860e257b744.png)

Code:
```javascript
      <Hero size="fullheight">
        <Hero.Body>
          <Container>
            <Content>
              <Button>Increment</Button>
              <Button>Something</Button>
              <Button>NOthings</Button>
            </Content>
          </Container>
        </Hero.Body>
      </Hero>
```

#### With plain html

![captura de pantalla 2019-02-14 a la s 8 13 19 p m](https://user-images.githubusercontent.com/10360816/52828025-1f021000-3095-11e9-8a20-0483e9974d21.png)

Code:
```html
         <div class="hero is-fullheight">
            <div class="hero-body">
                <div class="container">
                    <div class="content">
                        <button class="button">Increment</button>
                        <button class="button">Something</button>
                        <button class="button">NOthings</button>
                    </div>
                </div>
            </div>
        </div>
```

**Comment by jahirfiquitiva** [comment]
What's even more weird, is it happens even without using this library, so I wonder if it's a react thing 🤔 

```javascript
<React.Fragment>
  <div className="hero is-fullheight">
    <div className="hero-body">
      <div className="container">
        <div className="content">
          <button className="button">Increment</button>
          <button className="button">Something</button>
          <button className="button">NOthings</button>
        </div>
      </div>
    </div>
  </div>
</React.Fragment>
```

**Comment by Sparragus** [comment]
React is stripping out the white space between the buttons. When you don't use React, the newlines + the indentation count as a space, so that's what you're seeing between the buttons. 

Here's a [video](http://recordit.co/13raEkLqWp) showing what's up:
![image](http://g.recordit.co/13raEkLqWp.gif)

**Comment by jahirfiquitiva** [comment]
@Sparragus thanks for the detailed explanation.
Any tip of how to fix this? Maybe adding a `&nbsp;`?

**Comment by Sparragus** [comment]
@jahirfiquitiva In React, if you want a space between the buttons there are two things you could do:

```jsx
              <Button>Increment</Button>
              {' '}
              <Button>Something</Button>
              {' '}
              <Button>NOthings</Button>
```

or create a class that does something like:

```css
button + button {
  margin-left: 0.5rem;
}
```

**Comment by jahirfiquitiva** [comment]
Actually, I just gave it a try, and I can confirm this works! (although your other option with `{' '}` works too, @Sparragus )

Thank you so much for the help!

```javascript
<React.Fragment>
  <Hero>
    <Hero.Body>
      <Container>
        <Content>
          <Button>Increment</Button>&nbsp;
          <Button>Something</Button>&nbsp;
          <Button>NOthings</Button>&nbsp;
        </Content>
      </Container>
    </Hero.Body>
  </Hero>
</React.Fragment>
```
