### ISSUE TITLE
tilde bug

### ISSUE THREAD

**Issue by stydav** [couds/react-bulma-components#149]
@import "~_variables.sass" in lib/components/utils.sasss

should be

@import "_variables.sass"

**Comment by MrCreeper1008** [comment]
Would be great if you could make a PR on it since this looks like a simple fix.

**Comment by couds** [comment]
Hi @stydav I can't find the code you mention in master we alredy point to `_variables.sass` 

https://github.com/couds/react-bulma-components/blob/fe5dd566d1430745613d0e8619e75941fa6b546d/src/components/utils.sass#L3-L5
