### ISSUE TITLE
Disable next button on Pagination when making data fetch

### ISSUE THREAD

**Issue by kkomaz** [couds/react-bulma-components#150]
Currently, the previous and the next buttons are disabled when the user is on the first or last page.

Is it possible to disable the button when the user clicks NEXT so they don't have the option to continuously click through and make a bunch of async requests?  Thanks

![demo](http://g.recordit.co/7oiZwNlA0b.gif)

**Comment by kkomaz** [comment]
<img width="764" alt="screenshot of google chrome 2-20-19 5-23-10 pm" src="https://user-images.githubusercontent.com/8473884/53128964-3b3dfb00-3534-11e9-9a90-727cdf242d37.png">

Based on the image it doesn't seem like it~ :(

**Comment by MrCreeper1008** [comment]
Seems like it is hard-coded. Makes sense to make it a prop with default behavior instead. If @couds approves I'll implement this feature.
