### ISSUE TITLE
Bulma outdated, consider upgrading or make a peer dep?

### ISSUE THREAD

**Issue by pcr910303** [couds/react-bulma-components#154]
The Bulma CSS framework is outdated, (v0.7.1), which makes some components not same with the Bulma documentation. 
One of it is the progress bar, where if no value is specified, it is [supposed](https://bulma.io/documentation/elements/progress/#indeterminate) to render an indeterminate progress bar while it renders as value 0.

I fixed this by just bundling the Bulma CSS instead of the CSS provided here, but it would be better if the latest Bulma was a dependency, or make Bulma an peer-dependency, which would make people install the latest Bulma own self.

**Comment by MrCreeper1008** [comment]
Yep, this makes sense as this is sort of a plugin of Bulma, so Bulma should definitely be a peer dep. I'll work on this asap.

**Comment by MrCreeper1008** [comment]
@couds this is a breaking change.

**Comment by alanford123** [comment]
Since we are talking about improvement suggestions, I'd like to ask if it's possible to make so that we can always include from 'react-bulma-components' instead from specific paths such as ''react-bulma-components/lib/components/columns'

**Comment by couds** [comment]
Hi @MrCreeper1008 Please do not add bulma as a peer dependency, I want it to be a dependency to lock the version which this library its compatible. Its pending to update the version to last bulma version. If you can do that will be great! Thanks

**Comment by couds** [comment]
@alanford123, you have 2 ways to include the library. the basic that work as you want (`import { Columns } from 'react-bulma-components`) and advanced that use specific path to improve the tree shaking.

**Comment by MrCreeper1008** [comment]
@couds got it. I'll do it in my free time.

**Comment by MrCreeper1008** [comment]
I realized bulma was upgraded to 0.7.4 in #151.

**Comment by couds** [comment]
Fixed on fe5dd566d1430745613d0e8619e75941fa6b546d
