### ISSUE TITLE
Adding bulma helper classes as props

### ISSUE THREAD

**Issue by pcr910303** [couds/react-bulma-components#155]
I think it would be good to make some bulma [helper classes](https://bulma.io/documentation/modifiers/helpers/) applicable as props in such manner like [Bloomer](https://bloomer.js.org/#/documentation/overview/helpers).
Maybe better, integration with [bulma-helper](https://github.com/jmaczan/bulma-helpers) as an opt-in will be good.
It's just a suggestion, as I find such situations where bulma's css doesn't do things always 'right', and I get to write inline styles. I think it will be better to pass props to the component in a consistent manner.

**Comment by MrCreeper1008** [comment]
Can you give some examples?

**Comment by MrCreeper1008** [comment]
Sounds like a brilliant idea btw.

**Comment by couds** [comment]
Hi @MrCreeper1008 @pcr910303  The helpers classes are already in props (The base element have it, and all or almost all component of the library render as this element) 

you can find the code on https://github.com/couds/react-bulma-components/blob/master/src/modifiers.  Is that what you mean?

**Comment by MrCreeper1008** [comment]
Wow, TIL.
This is pretty hidden though; do you think we should create a better documentation?

**Comment by couds** [comment]
Yes. I need it to. I just bought a domain to create the home page. I need to find some time to do it.

**Comment by pcr910303** [comment]
Wow, I didn’t realize about the helper classes! Really need some documentation of the props :-( as I find myself reading the source... Maybe I can help for the docs? 
BTW, are you interested in integrating with [bulma-helper](https://github.com/jmaczan/bulma-helpers)?
There are situations where bulma’s CSS doesn’t really look right... and I would appreciate if styling can be handled in a more consistent manner.

**Comment by MrCreeper1008** [comment]
@couds alternatively you can consider making the documentation open source and host it for free on github :)

**Comment by couds** [comment]
Closing this. we already have the helpers.
