### ISSUE TITLE
Library Logo

### ISSUE THREAD

**Issue by couds** [couds/react-bulma-components#156]
Hi Guys!

I'm looking for someone to helpme to create a cool logo for this library. I started this library as a hobby, but now that we have a lot of people using it I want to give this a respetable logo (I'm really really bad on design). If you want to help post here a logo proposal.

Thanks all for your support. This new logo will be included on the Readme and the new Webpage I'm creating for this library

**Comment by MrCreeper1008** [comment]
I'll try!

**Comment by couds** [comment]
![bulma-react-components](https://user-images.githubusercontent.com/2903371/53641078-2cd79980-3c2e-11e9-9305-fc39857248e2.png)

We have a logo! =)

**Comment by MrCreeper1008** [comment]
Wow, looks nice! I would suggest moving the react logo slightly to the left though.
