### ISSUE TITLE
Using react-bulma-components navigation with react-router

### ISSUE THREAD

**Issue by alanford123** [couds/react-bulma-components#157]
Dear @couds , thanks for your work so far!

I've one issue I'd like to voice: using the `<Navbar/>` component doesn't work natively with react-router-dom. React router uses a `<Link>` component to render an `<a>` html element, but so does your `<Navbar.Item>`. So the two can not be used together.

Right now there's a workaround, by passing `className={"navbar-item"}` to the `<Link>` component. 

Do you think there's a better way around this?

**Comment by MrCreeper1008** [comment]
Use the `renderAs` prop and render navbar item as a `<Link />`. I had used this library with React router before and they worked perfectly together.

**Comment by alanford123** [comment]
lovely, thank you!

**Comment by MrCreeper1008** [comment]
No problem!

**Comment by martinfjant** [comment]
Using NavLink and having access to weather it's active or not is not possible though :(..
