### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by gregorskii** [couds/react-bulma-components#158]
Hi,

The storybooks are great, but I don't find they adequately show how to use the component without looking at the source of the lib, or the storybook.

I think it would make sense to add a documentation site that shows how to use each component without pointing directly to bulma. The pure CSS documentation from bulma does not directly translate to how this library uses those classes.

WDYT?

Thanks a ton for this lib. Its great otherwise.

**Comment by MrCreeper1008** [comment]
We're working on it: https://github.com/couds/react-bulma-components/issues/155#issuecomment-467761619

**Comment by gregorskii** [comment]
Awesome. Thank you very much!
