### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `active`.

### ISSUE THREAD

**Issue by alanford123** [couds/react-bulma-components#160]
I've implemented the active prop for navbar as such `<Navbar active={('Active', this.state.open)}>` or alternatively as such `<Navbar active={this.state.open}>` or as such `<Navbar active={(this.state.open)}>`
where `this.state.open: false` 
Implementing the active prop for navbar results in a react warning:

```
Warning: Received `false` for a non-boolean attribute `active`.

If you want to write it to the DOM, pass a string instead: active="false" or active={value.toString()}.

If you used to conditionally omit it with active={condition && value}, pass active={condition ? value : undefined} instead.
    in div (created by Element)
    in Element (created by Context.Consumer)
    in NavbarMenu (at Menu.js:55)
    in nav (created by Element)
    in Element (created by Navbar)
    in Navbar (at Menu.js:38)```

**Comment by MrCreeper1008** [comment]
@couds This is a bug. In this line,
https://github.com/couds/react-bulma-components/blob/fe5dd566d1430745613d0e8619e75941fa6b546d/src/components/navbar/context.js#L3
the value passed to `React.createContext()` should be a Boolean value, not a string,  

I will fix this asap.

**Comment by MrCreeper1008** [comment]
@alanford123 do keep in mind though, among all three values you've tried passing to the `active` prop, only the second one is correct; the other two, namely:
 - `<Navbar active={('Active', this.state.open)}>`
-  `<Navbar active={(this.state.open)}>`  

 are syntactically incorrect and thus will not produce anything meaningful.
