### ISSUE TITLE
Wrong props passed to <Box /> in box.story.js

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#163]
In `box.story.js`, the `responsive` prop is given an object with a wrong shape, resulting in these errors:

![boxjs-error](https://user-images.githubusercontent.com/19359984/53676918-b1382400-3ce3-11e9-9244-0d54649c9457.png)  

For example, in  
https://github.com/couds/react-bulma-components/blob/fe5dd566d1430745613d0e8619e75941fa6b546d/src/components/box/box.story.js#L17  

`display` is a string, when, according to the propTypes defined in `responsives.js`, should be:  
```
display: PropTypes.shape({
  value: PropTypes.oneOf(displays),
  only: PropTypes.bool,
}),
```

**Comment by couds** [comment]
Hi @MrCreeper1008 Yes I saw that yesterday. Already fixed on 5a3bc89bc6d0630b2e574ea7656ca978257298e9
