### ISSUE TITLE
TypeScript basic usage: "JSX element type 'Button' does not have any construct or call signatures."

### ISSUE THREAD

**Issue by lukewlms** [couds/react-bulma-components#165]
On @next: I'm trying to set up a very simple project and getting this error when attempting to use any component.

The .d.ts definitions appear to only export <Button /> as an extension of a props type, not a JSX element constructor.  How do I get around this?  (@dfee)

Minimal repro:

```
import { Button } from "react-bulma-components";
const SomeComponent = () => <Button />;
```

**Comment by couds** [comment]
Hi @lukewlms Can you test the version v3.0.1-3 `npm i react-bulma-components@v3.0.1-3` and check if you have the error? That was probably a error I introduce in the latest version.

**Comment by lukewlms** [comment]
@couds Yes, that release works!   Thanks a lot - excited about the potential of this library for my team, we're huge Bulma and React fans.

**Comment by MWin123** [comment]
The bug seems to be back in `react-bulma-components@3.0.1-4`.

> TS2604: JSX element type 'Button' does not have any construct or call signatures.

**Comment by couds** [comment]
Yes that version have an issue on the TS definitions. please use the previous one, I didnt had the change to fix it or revert it =(
