### ISSUE TITLE
Inconsistency across documentation

### ISSUE THREAD

**Issue by libasoles** [couds/react-bulma-components#167]
Hi. I installed "react-bulma-components": "^2.3.0".

I've been trying to get this working for a couple of days with no luck.

According to **npm** documentation (https://www.npmjs.com/package/react-bulma-components), I should crate an **alias** to **_variables.sass**. As I don't use webpack, I managed to do that with a plugin:

`npm i --save-dev link-module-alias`

And then in **package.json**
```
"_moduleAliases": {
    "_variables.sass": "src/scss/_variables.sass"
  },
```

Anyway it fails, because inside _variables I have a call to:
`@import '~bulma/sass/utilities/initial-variables.sass'`

And that cannot be resolved:
"File to import not found or unreadable: ~bulma/sass/utilities/initial-variables.sass.",

Where does **~** come from? Is it another alias?

---

Now, there's this other tutorial (not official: https://hackernoon.com/building-a-website-with-react-and-bulma-d655214bff2a) that has a couple of nice details regarding chokidar executing. And it imports the scss like this, without **~**:
`
@import "bulma/sass/utilities/initial-variables";`

That almost works. However, I get this error:
`File to import not found or unreadable: ~_variables.sass.`

Like I'm forced to declare that file in a given path (maybe related to ~). But who is throwing that error? Well, seems like this guy does:

`import Columns, {Column} from 'react-bulma-components/lib/components/columns';`

But wait, there`s nothing in npm documentation telling that I should declare my sass file in my root folder or something. However... there is something mentioned in v3.... on github:

https://github.com/couds/react-bulma-components#advanced

There you can read:
"Now the alias needed to override Bulma variables (and/or use the directly the sass files) is _variables.sass instead of ~_variables.sass"

But wait, the old npm documentation never mentioned the ~ in the alias. It just says:
```
alias: {
        '_variables.sass': path.resolve(__dirname, 'relative/path/from/webpack/config/to/your/_variables.sass'),
      },
```

Anyway, making it "~_variables.sass" wont work either. Same error (at least not using webpack but the plugin I mentioned, as I use just CRA).

So... I'm kinda lost. Hope that with v3 released the docs will be cleared. However... I must say I've been reading that docs and I totally disagree with the `NODE_PATH=./src` workaround. Does that means that I must place my sass file there instead of in a proper styles folder?

**Comment by couds** [comment]
Hi @libasoles thanks for using (or trying to use) this library.

For the version 2.x to use the advance setup as you saw you need to create an alias, that's because the library need to import de variables from outside the node_modules.

The initial-variables.sass comes from Bulma and the ~ mean that should be loaded from the node_modules folder (that isn't a alias) IDK why that's fail to you. Can you put an example project were I can reproduce the issue?

About V3 and the where to put the variables file: the `src` folder it's an example you can put the file wherever you want just changing the env variable. For example

If your variable.sass files it's on `src/styles/sass/_variables.sass` in CRA you should change the scripts with `NODE_PATH=./src/styles/sass/`

I hope this clear a little how RBC works. I'm working on better documentation but takes some time.

**Comment by libasoles** [comment]
Thanks for your (quick) reply. Sure it takes time. Anyway, Storybook and all you have done is great, so thanks for sharing.

Problem with `NODE_PATH `is that it's sometimes used to resolve absolute paths. For example: 
https://github.com/facebook/create-react-app/issues/2188#issuecomment-302040874

So, pointing that var to a scss folder is not good. And if I just point to `/src`, then i'm being forced to declare a sass file outside of the styles folder. 

That being said, I did pointed `NODE_PATH  `to the folder, placed my variables there, and I've got it running, without the need of _chokidar_. Cool. I can't override vars by now, for some reason, but at least the project works now with the "advanced configuration".

Hope to see the v3 soon. Any plans to release typescript @types? (I know, off topic question)

**Comment by couds** [comment]
Hi.

About the NODE_PATH variable you can have multiple paths like this `NODE_PATH=./src:./src/your/sass/path` that way you can have both path resolved as root module directories.

About typescript I do not use it so I depend of the community for adding TS support =(

**Comment by HJerem** [comment]
@couds Did you manage to use react bulma components with CRA ? I'm still having hard time figuring out how to make it works...

**Comment by MrCreeper1008** [comment]
@HJerem it should work fine with CRA (I have a CRA project that uses react-bulma-components). Should be as simple as doing an npm i.

**Comment by HJerem** [comment]
> @HJerem it should work fine with CRA (I have a CRA project that uses react-bulma-components). Should be as simple as doing an npm i.

Well, I don't express myself well. I'm trying to make it work AND override Bulma's variables. Did you succeed to do that ?

**Comment by couds** [comment]
Hi @HJerem right now only v3 is compatible with CRA with variable override (there are probably some workaround but idk XD). 

I'm working on  public page with better docs and I'm using CRA and this library to build it, you can check the code here https://github.com/couds/react-bulma-components/tree/feature/public-page/public that is a working example of this library with CRA. 

Note that I'm working on a brakeing change on the way we import/use to by default be the advanced configuration. IDK if I'm going to publish that change on V3 or V4. so keep an eye when the v3 become the latest stable.

**Comment by MrCreeper1008** [comment]
@couds will the new doc be open source?

**Comment by couds** [comment]
@MrCreeper1008 Yes, you can find it on the link https://github.com/couds/react-bulma-components/tree/feature/public-page/public (will be on the public folder of this repo, but currently its on the public-page branch

**Comment by MrCreeper1008** [comment]
Cool! Thanks.

**Comment by HJerem** [comment]
> Hi @HJerem right now only v3 is compatible with CRA with variable override (there are probably some workaround but idk XD).
> 
> I'm working on public page with better docs and I'm using CRA and this library to build it, you can check the code here https://github.com/couds/react-bulma-components/tree/feature/public-page/public that is a working example of this library with CRA.
> 
> Note that I'm working on a brakeing change on the way we import/use to by default be the advanced configuration. IDK if I'm going to publish that change on V3 or V4. so keep an eye when the v3 become the latest stable.

How can I help ? I really want to use these components, and so I need V3 out (and V4 if it's needed for CRA + variables override) 😄

**Comment by couds** [comment]
I finally release v3 as the latest version the inconsistency on the docs should be solved. Open this again if you find something else.

Thanks
