### ISSUE TITLE
Button component outlined usage should be available without any modifier

### ISSUE THREAD

**Issue by jcleefw** [couds/react-bulma-components#168]
The usage of outlined is only available when the modifier of the button is define life `is-primary`, `is-link`

I want to be able to use the button as below
```
<Button outlined={true}>Text</Button>
```

**Comment by MrCreeper1008** [comment]
I'll take a look. Thanks!

**Comment by couds** [comment]
Hi @jchapple That is a behavior of Bulma.io you should add that request on the Bulma.io github not here, we add the corresponding class 
![image](https://user-images.githubusercontent.com/2903371/54765641-29667b00-4bfa-11e9-8674-4dd01cecf72f.png)
