### ISSUE TITLE
Bulma Styles not being imported on Gatsby Build

### ISSUE THREAD

**Issue by jacksaunders** [couds/react-bulma-components#171]
I am using v3 of this repo with a gatsby v2 site. 

i am importing the components like so

`import {  Field,  Control,  Label,  Input, Help,} from 'react-bulma-components/lib/components/form'`

All is working fine when running `gatsby develop` and the styles are imported from the `form.sass` file in the bulma node_modules folder.

However when i run `gatsby build` none of the Bulma styles are being imported. 

This is my gatsby sass config

```
{
      resolve: `gatsby-plugin-sass`,
      options: {
        includePaths: ['./src', './node_modules'],
      },
    },
```

I have tried both with and without `node_modules` in the `includePath`

i assume this is a webpack issue but i cant quite work out whats going on.

**Comment by HJerem** [comment]
Seems to be an issue related to `gatsby-plugin-sass`. What's your version ?
Try to lock your `gatsby-plugin-sass` to version `1.0.19` if you are on `1.0.20`.
Check this issue : [Styles missing from build when using gatsby-plugin-sass with CSS modules](https://github.com/gatsbyjs/gatsby/issues/4457)

**Comment by jacksaunders** [comment]
i'm using version `2.0.11` of `gatsby-plugin-sass`

**Comment by couds** [comment]
This is still happening? the Gatsby issue is solved

**Comment by couds** [comment]
Closing this due inactivity
