### ISSUE TITLE
Disable Hamburger option on navbar?

### ISSUE THREAD

**Issue by kkomaz** [couds/react-bulma-components#174]
Is there a good way to disable the hamburger option in the navbar?  For example when the screen gets smaller, I just want it to retain the original nav bar settings in the `<Navbar.Menu>`

**Comment by MrCreeper1008** [comment]
No. This is a Bulma behavior and we can't do anything about it. You can manually adjust the threshold of what is considered too small for it to become a hamburger menu but that's about it.

**Comment by kkomaz** [comment]
is there a key or prop for that?

**Comment by MrCreeper1008** [comment]
This may help you: (Bulma doc)[https://bulma.io/documentation/modifiers/responsive-helpers/#hide]  
As for how to use them with this libraries, refer to (here.)[https://github.com/couds/react-bulma-components/blob/master/src/modifiers/responsives.js]  

Documentations on how to use Bulma modifiers aren't exactly clear, though a new documentation is in the pipeline, and I hope it'll make it easier for developers to use this library.

**Comment by kkomaz** [comment]
Yea no worries.  If things have failed i've been going back to the original bulma library and building it the old fashioned way :)  Just wanted to confirm

**Comment by MrCreeper1008** [comment]
Modifiers should work perfectly with this library. Every component in this library accepts prop types defined in the file I linked previously. Just copy the value from Bulma doc and it should work.
