### ISSUE TITLE
Multiple dropdowns unable to open unless hoverable

### ISSUE THREAD

**Issue by carlbarrdahl** [couds/react-bulma-components#176]
Seems to be issues when more than one dropdown is rendered on page.

**Comment by couds** [comment]
Hi @carlbarrdahl please provide a working example where we can reproduce the issue. Thanks

**Comment by carlbarrdahl** [comment]
Yes of course: https://codesandbox.io/s/w7pow0yxr7

**Comment by couds** [comment]
Thanks for reporting it, This will be available on the next prerelease
