### ISSUE TITLE
Path to _variables.sass from utils.sass is wrong

### ISSUE THREAD

**Issue by nerdstep** [couds/react-bulma-components#178]
Version: `3.0.1-4`

In `lib/components/utils.sass` the import path is `_variables.sass`, however it should be `../_variables.sass`.

**Comment by couds** [comment]
Hi @nerdstep thank for reporting it but no its not incorrect,  we use absolute import for the sass to allow overriding that file with your own variables,  check the instruction of the advance configuration https://github.com/couds/react-bulma-components#advanced
