### ISSUE TITLE
Heading sizes

### ISSUE THREAD

**Issue by RobLoach** [couds/react-bulma-components#18]
https://couds.github.io/react-bulma-components/?selectedKind=Heading&selectedStory=Default&full=0&down=0&left=1&panelRight=0

``` html
<Box>
  <Heading size={2}>
    Title
  </Heading>
  <Heading subtitle size={4}>
    Subtitle
  </Heading>
</Box>
```

Ends up with two `h1`s rather than one `h1` and one `h2`.

**Comment by couds** [comment]
Hello! The size of the heading works to add the className righr now. To change the html element you need to pass the renderAs prop with the name of the html attrbute or another React Class/function like this

```
<Box>
  <Heading renderAs={OtherComponent} size={2}>
    Title
  </Heading>
  <Heading renderAs="h2" subtitle size={4}>
    Subtitle
  </Heading>
</Box>
```

In this example the first heading will render as whatever render the `OtherComponent` and the second one as an `h2` element.

I hope this solve yoir issue. If you have any other question or find a bug feel free to write.

Thanks for using this module =)

**Comment by RobLoach** [comment]
Good to know! Added some changes into the storybook over at https://github.com/couds/react-bulma-components/pull/19 about `renderAs`... Pretty awesome! Thanks a lot.

**Comment by couds** [comment]
Thanks. I will close this issue then.
