### ISSUE TITLE
[TypeScript] Can't pass extra props when using `renderAs`

### ISSUE THREAD

**Issue by ThunderDev1** [couds/react-bulma-components#182]
For example, if I'm using react-router, to add links to the navbar, I need to do something like this:

`<Navbar.Item renderAs={Link} to="/page1">Page 1</Navbar.Item>`

I get a TS error saying `to` prop is not supported by Navbar.Item. To get around this I simply use the css class on my Link component

`<Link className="navbar-item" to="/page1">Page 1</Link>`

Is there a better way ? I'm not sure if it's possible to accept props from the component passed to `renderAs`

**Comment by MrCreeper1008** [comment]
I think you should be able to use props of the component passed to `renderAs` directly; it works fine for me. Can you reproduce this issue with vanilla JavaScript?

**Comment by ThunderDev1** [comment]
This is purely a TypeScript problem. The code runs fine, but I get a type error in my editor (vs code)

Here is an example https://github.com/ThunderDev1/react-ts-parcel/tree/bulma-ts-error

**Comment by couds** [comment]
@ThunderDev1 currently the TS support on this librery its quite poor (I do not use TS so I didnt added support =( I have an issue opened to improve the TS support asking for help. sorry

**Comment by couds** [comment]
Thanks to @kennethnym now renderAs prop work correctly on TS 🎉  Closing this

![image](https://user-images.githubusercontent.com/2903371/115766662-810edc00-a3a8-11eb-85dd-4cbbcd622fee.png)

![image](https://user-images.githubusercontent.com/2903371/115766774-a1d73180-a3a8-11eb-843a-e56d03feb2c3.png)
