### ISSUE TITLE
Hero from 'react-bulma-components/lib/components/hero' forwarding props to the DOM 

### ISSUE THREAD

**Issue by alanford123** [couds/react-bulma-components#187]
The `Hero from 'react-bulma-components/lib/components/hero'` component forwards props to the DOM causing an error:

`Warning: React does not recognize the `isDayTime` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdaytime` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

![image](https://user-images.githubusercontent.com/11723882/57969789-60e37080-797a-11e9-95cb-ed545010301e.png)

This can is caused by passing a prop to the Hero component, as such:
`<HeaderHero subtitle>`
And it will be cause an error.
![image](https://user-images.githubusercontent.com/11723882/57969893-d2232380-797a-11e9-8199-41e4eee1af65.png)
![image](https://user-images.githubusercontent.com/11723882/57969899-d8190480-797a-11e9-9e99-ea8fde922885.png)

**Comment by couds** [comment]
Hi. All components int his library pass down the props to the children. It's the developers responsibility to clean the props before passing it to the component. 

The prop `isDayTime` and `subtitle` are not valid props for the Hero component

**Comment by alanford123** [comment]
Thanks @couds. Indeed using destructuring solves the issue. I've run into this with using styled-components together with react-bulma-components, and passing props to styled components for conditional CSS rules. The solution, for anyone looking at this in the future can be found here:
https://github.com/styled-components/styled-components/issues/135

just use code as such:
```const ListElement = styled(({ active, ...rest }) => <Link {...rest} />)```
