### ISSUE TITLE
navbar/components/menu.js: Warning: Received `false` for a non-boolean attribute `active`.

### ISSUE THREAD

**Issue by alanford123** [couds/react-bulma-components#188]
Recieving the following error on Navbar.Menu:

```javascript
index.js:1446 Warning: Received `false` for a non-boolean attribute `active`.

If you want to write it to the DOM, pass a string instead: active="false" or active={value.toString()}.

If you used to conditionally omit it with active={condition && value}, pass active={condition ? value : undefined} instead.
    in div (created by Element)
    in Element (created by Context.Consumer)
    in NavbarMenu (at Menu.js:103)
    in nav (created by Element)
    in Element (created by Navbar)
    in Navbar (created by Context.Consumer)
    in StyledComponent (created by Styled(Navbar))
    in Styled(Navbar) (at Menu.js:72)
    in Menu (at Header.js:159)
    in header (created by Context.Consumer)
    in StyledComponent (created by styled.header)
    in styled.header (at Header.js:148)
    in Header (created by Route)
    in Route (created by withRouter(Header))
    in withRouter(Header) (at App.js:119)
    in div (at App.js:104)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.js:103)
    in App (at src/index.js:7)
```

Code
` <Navbar.Menu active={this.state.open}>`

![image](https://user-images.githubusercontent.com/11723882/57970051-d9e3c780-797c-11e9-9243-0f361c4818ad.png)

File in question:
https://github.com/couds/react-bulma-components/blob/master/src/components/navbar/components/menu.js

**Comment by couds** [comment]
Hi. The active prop need to be defined on the Navbar component not in the Navbar.Menu component. This prop will be propagated using the context

**Comment by alanford123** [comment]
Thank you very much! Perhaps than, the storybook manual can be updated to help others? :)
![image](https://user-images.githubusercontent.com/11723882/58203160-c5376480-7cd9-11e9-97d4-44148caabf5d.png)

**Comment by couds** [comment]
Yes currently the storybook its from v2 (because I didnt release v3 as the latest version yet) :(
