### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by PatrickGTR** [couds/react-bulma-components#193]
Is there a list of Icons when using, tried looking through the source code but had issues finding.  The documentation doesn't say it as well.
https://couds.github.io/react-bulma-components/?selectedKind=Icon&selectedStory=Custom%20Icon&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel 

```js
<Icon icon="insert-icon-name" />
```

**Comment by MrCreeper1008** [comment]
The `icon` prop takes in an icon name from FontAwesome.
