### ISSUE TITLE
Columns `is-vcentered`

### ISSUE THREAD

**Issue by pcr910303** [couds/react-bulma-components#194]
Is [`is-vcentered`](https://bulma.io/documentation/columns/options/#vertical-alignment) also covered?̊̈

I cannot see any mention about center in the [corresponding code](../blob/master/src/components/columns/columns.js).

**Comment by couds** [comment]
Hi @pcr910303 sorry for the wait, currently its not on the library (I think this props was added later to bulma) I will try to add it as soon as I can, currently I'm quite busy but I will try my best. (Also PR's are welcome) ;-)

**Comment by MrCreeper1008** [comment]
@couds I'll do that
