### ISSUE TITLE
navbar with dropdown

### ISSUE THREAD

**Issue by bobman38** [couds/react-bulma-components#204]
Following case #91 I can't see a way to create a navbar with dropdown 😄 

The storybook don't show any element regarding `<Navbar.Dropdown>` component but there is [one](https://github.com/couds/react-bulma-components/blob/master/src/components/navbar/components/dropdown.js) !

Who have a working example of a navbar-dropdown element ?

THANKS !

**Comment by unrealsolver** [comment]
```jsx
<Navbar.Item dropdown={true} hoverable={true}>
  <Navbar.Link>User Name</Navbar.Link>
  <Navbar.Dropdown>
    <Navbar.Item>Settings</Navbar.Item>
    <Navbar.Divider />
    <Navbar.Item>Log Out</Navbar.Item>
  </Navbar.Dropdown>
</Navbar.Item>
```

**Comment by bobman38** [comment]
bom thanks that's answer my question ! I will raise a PR on the stoybook 😃
