### ISSUE TITLE
Issue on props warnings for renderAs when using forwardRef

### ISSUE THREAD

**Issue by DimitarChristoff** [couds/react-bulma-components#206]
https://codesandbox.io/s/confident-northcutt-bbt9v

usecase: `react-router-dom`'s `Link` element, see https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L70

uses `forwardRef` which returns an `object` whereas your definition is `oneOf` accepting `string`, `function`

more: https://reactjs.org/docs/forwarding-refs.html

**Comment by couds** [comment]
This is fixed on version 3 (`npm i --save -E react-bulma-components@next`)

**Comment by DimitarChristoff** [comment]
we are using 3.0.0-7 atm. I've updated the code sandbox. https://codesandbox.io/s/confident-northcutt-bbt9v

open the console, then reload the result. you get:

![image](https://user-images.githubusercontent.com/119500/66219831-c9ca4b80-e6c3-11e9-9010-d7594f2fde93.png)

**Comment by couds** [comment]
Hi, IDK why this didn't happen on my project (maybe this is an issue on the basic configuration build, but now its fixed on version `3.1.2` https://codesandbox.io/s/late-wave-o97zy 

![image](https://user-images.githubusercontent.com/2903371/66257364-7aa21a80-e798-11e9-9771-d8e79c3403a0.png)
