### ISSUE TITLE
[documentation] forwardRef API

### ISSUE THREAD

**Issue by DimitarChristoff** [couds/react-bulma-components#208]
just a quickie this time (I promise...)

usecase: 
```js
const navEl = React.createRef();
<Navbar ref={ref}/>

...
navEl.current == null 
```
correct: 

```js
const navEl = React.createRef();
<Navbar domRef={ref}/>

...
navEl.current; // HTMLElement 
```

Looking at your source, you use `domRef=` which is not listed as API anywhere on the component element pages, though it's in https://couds.github.io/react-bulma-components/?path=/story/element--default - you need to read the source and see how that recomposes

may be good to document it or to use forwardedRef or something more commonly used at large. https://reactjs.org/docs/forwarding-refs.html

**Comment by MrCreeper1008** [comment]
Where is the repo for the doc?

**Comment by couds** [comment]
@MrCreeper1008 this one, currently only the Readme and the storybook. the public page is WIP (in this repo on the branch https://github.com/couds/react-bulma-components/tree/feature/public-page

**Comment by MrCreeper1008** [comment]
ill make a quick pr for that. thanks!
