### ISSUE TITLE
Error with: @import "_variables.sass"

### ISSUE THREAD

**Issue by Pitbi** [couds/react-bulma-components#209]
Hello,

With the latest version, I have the following error:

`
@import "_variables.sass"
      File to import not found or unreadable: _variables.sass.
      in .../node_modules/react-bulma-components/lib/components/utils.sass (line 3, column 1)
`

When I import:

`
import {
  Field,
  Control,
  Label,
  Input,
} from 'react-bulma-components/lib/components/form'
`

It works if I delete It works if I delete line 3 from the `utils.sass` file.

Do you have the same problem?

Thanks for reading me :)

**Comment by couds** [comment]
Hi @Pitbi did you setup the path to your `_variables.sass` file? 

check https://github.com/couds/react-bulma-components#advanced

Also please provide your configuration or a example project where we can replicate the issue

**Comment by Pitbi** [comment]
Oops... Sorry it's my fault.

I was a little fast in the Gatsby configuration ... I forgot `includePaths` in the `gatsby-plugin-sass` options.

Thanks for the answer anyway!
