### ISSUE TITLE
Configuration Example for Parcel

### ISSUE THREAD

**Issue by baronnoraz** [couds/react-bulma-components#210]
This is a request to add a configuration example for Parcel (if anyone has a working example!).  I have been unable to get this to work.  I always get `Can't find stylesheet to import` `@import "_variables.sass"`.  Thanks!

**Comment by icyJoseph** [comment]
First thing is to have `"_variables.sass"` at the very top, for example, `project/src/_variables.sass`. I reckon you've read a bit on Parcels' [documentation](https://parceljs.org/scss.html) and this [already solved issue](https://github.com/parcel-bundler/parcel/issues/1836) - I'll give it a go and see how it goes, but please do try having `"_variables.sass"` at the top entry level of your project.

**Comment by MrCreeper1008** [comment]
@icyJoseph would be great if you can create a minimal example so I can add instructions on how to configure this library with parcel in the new documentation. thank you!

**Comment by steveblue** [comment]
`@import "_variables.sass"` is improper syntax. All you should need is `@import "variables"`

**Comment by couds** [comment]
@baronnoraz this is still an issue?

**Comment by baronnoraz** [comment]
I'll give it try tonight and see. Thanks for following-up everyone

**Comment by jamwaffles** [comment]
> All you should need is @import "variables"

That seems to fix it for me, thanks for the tip. Magic! Maybe not in a good way lol...

**Comment by couds** [comment]
In V4 we are dropping the generation of the styles in favor to allow each developer to include the bulma classes in the way their framework does it
