### ISSUE TITLE
Is jsconfig.json necessary for CRA?

### ISSUE THREAD

**Issue by RobJacobson** [couds/react-bulma-components#219]
I'm relatively new to React. I found the instructions for integrating with SASS and create-react-app rather confusing.

In particular, the documentation states the following: 

> Now create/update your jsconfig.json (or tsconfig if you are using typescript)
> {
>   "compilerOptions": {
>     "baseUrl": "./src"
>   }
> }

However, CRA doesn't include a jsconfig file by default. The documentation here doesn't explain how/where/why to create this file. Is this step required? This was a pain point for me.

I was also confused by discussion of the _variables.sass file.  I couldn't tell whether this particular name is required due to some "magic words," or if it was just a suggestion.  It doesn't explain how to integrate the variables file into your main .js/.jsx components.

This tutorial shows how to set up a basic Bulma/SASS configuration in CRA, although it doesn't use react-bulma-components.  It lets you use any naming convention for your variables file and explains how to integrate these into your component files. It doesn't mention any need for jsconfig.

https://scotch.io/tutorials/using-sass-in-create-react-app-v2

More generally, I think that react-bulma-components could benefit strongly from a simple "getting started" page that includes sample cut-and-paste code for CRA as the baseline.  (Most React tutorials today start with CRA, not other frameworks.)

I would love if an introduction could be written at the same level of generality as the official Bulma docs, with similar example code.  E.g., "Step one, do this....  Step two, do that.... Step three, do this other thing.... Now run npm start to see the results in your browser."  It should be simple enough so that any code monkey (like me) could follow it verbatim and get a successful result.

https://bulma.io/documentation/customize/with-node-sass/

Thanks!

**Comment by couds** [comment]
Hi

We are currently working on a public page with a better documentation. 

The current documentation for the advance configuration assumes the developer have some knowledge Of the framework.

**Comment by couds** [comment]
Hi

We are currently working on a public page with a better documentation. 

The current documentation for the advance configuration assumes the developer have some knowledge Of the framework.
