### ISSUE TITLE
Create rbc documentation based on official Bulma documentation?

### ISSUE THREAD

**Issue by RobJacobson** [couds/react-bulma-components#220]
I'd like to offer a friendly suggestion. I find the documentation on the Bulma homepage to be really beautiful and clear. It organizes the content into different categories (e.g., modifiers, columns, and layout) and subcategories. It then provides simple code examples for copy-paste coding.

In contrast, I'm finding the Storybook documentation for this project difficult to follow as a Bulma beginner. There's lots of code, but much of the code is boilerplate that causes visual noise and obscures the important content. There also isn't much in the way of explanation. 

As someone said, "good artists copy, great artists steal."  Since the Bulma documentation is licensed under MIT, why not just "steal" the documentation more-or-less verbatim and then make appropriate revisions to the code to use react-bulma-components?  

I'm looking to get involved with an OSS project and this could be something up my alley.  If you'd like, I could try "translating" a few existing Bulma documentation pages as an example.

(As a courtesy, we should run this proposal by @jgthms first.  However, I'm betting that he'd be cool with this, since it would make it easier for people to get started with using Bulma in React.)

Thanks!

**Comment by RobJacobson** [comment]
By the way, I realize that you're working on better documentation.  Hence the suggestion.  :-)

**Comment by couds** [comment]
Hi @RobJacobson Thanks the idea is just as just suggest its to have the documentation page like the bulma.io docs, you can check the WIP on https://react-bulma.dev and contribute on this [branch](https://github.com/couds/react-bulma-components/tree/feature/public-page). and the translations are in [Crowdin](https://crowdin.com/project/react-bulma-components)
