### ISSUE TITLE
Using RBC for the Divjoy component library

### ISSUE THREAD

**Issue by gragland** [couds/react-bulma-components#227]
Hey there, I run http://divjoy.com and I'm interested in rebuilding our library of templates and components using react-bulma-components. I'd also potentially be able to help out and financially support development of this project. @couds Is there a good email address or place we could chat?

**Comment by MrCreeper1008** [comment]
Sounds great!!

**Comment by couds** [comment]
I'm closing this due @gragland and I already talked. =)
