### ISSUE TITLE
Bulma Extensions

### ISSUE THREAD

**Issue by navotaras** [couds/react-bulma-components#23]
Hello - pls let us know if you are planning to consider adding some of the cool features of bulma-extensions. 

https://github.com/Wikiki/bulma-extensions

Thanks,
Naveen

**Comment by couds** [comment]
Hello! Maybe but I need to check which one can I integrate. Do you have a especific request?

**Comment by couds** [comment]
After considering I dont think I will add the extensions to this module. Maybe later I will create another module for the extensions but I will not add any extension to the main module.

Thanks
