### ISSUE TITLE
[TypeScript] - Can't set button type attribute

### ISSUE THREAD

**Issue by clehene** [couds/react-bulma-components#230]
<img width="701" alt="Screen Shot 2020-01-16 at 5 33 52 PM" src="https://user-images.githubusercontent.com/101597/72577166-8cf71e80-3886-11ea-9d3a-0e0b275bec8b.png">

```
TS2322: Type '{ children: Element; type: string; disabled: boolean; color: "primary" | "light"; loading: boolean; onClick: () => Promise<void>; }' is not assignable to type 'IntrinsicAttributes & ButtonProps & RefAttributes<any>'.   Property 'type' does not exist on type 'IntrinsicAttributes & ButtonProps & RefAttributes<any>'.
```

**Comment by clehene** [comment]
Not a bug. This should be passed as `submit` attribute. 
I seem to hit this repeatedly. Couldn't `Button` instead inherit `ButtonHTMLAttributes`
```
 interface ButtonHTMLAttributes<T> extends HTMLAttributes<T> {
        autoFocus?: boolean;
        disabled?: boolean;
        form?: string;
        formAction?: string;
        formEncType?: string;
        formMethod?: string;
        formNoValidate?: boolean;
        formTarget?: string;
        name?: string;
        type?: 'submit' | 'reset' | 'button';
        value?: string | string[] | number;
    }
```

**Comment by MrCreeper1008** [comment]
I'll look into it. Thanks!

**Comment by MrCreeper1008** [comment]
If you want to set the type of the button as submit, pass down a `submit` boolean prop. Same for reset type. I think `type=` is more natural though. cc @couds

**Comment by nielvid** [comment]
type?: 'submit' | 'reset' | 'button';  this solves the problem for me.

**Comment by kbradley** [comment]
How would you define `type="button"` as the default value if a type value isn't passed?

For example if the component was used just as `<Button>Click me</Button>` I would want the HTML under the hood to render as: `<button type="button">Click me</button>`

**Comment by couds** [comment]
Hi @kbradley if you want to do that, you will need to wrap the Button component, something like this

```jsx
const MyButton = (props) => {
  return <Button type="button" {...props} />;
}
```

**Comment by kbradley** [comment]
Hi @couds, thanks. I'm already doing that.

```
export interface ButtonProps {
    label: string,
    // Trying to figure out how to define 3 possible button type values with type="button" as the default value if unset
    // type: ('button' | 'submit' | 'reset') = 'button', // this is obviously wrong...
}

const Button = (props: ButtonProps) => {
    return (<button type={props.type}>{props.label}</button>
    );
};
```

**Comment by jay-cascade** [comment]
Why does this not work for me?

type props = {
 actionType?: Pick<ButtonHTMLAttributes<HTMLButtonElement>, "type">
}

If I then assign default in props destructuring like this: ({ actionType = "submit"}) IDE complains! 

With:

Type '"submit"' has no properties in common with type 'Pick<ButtonHTMLAttributes<HTMLButtonElement>, "type">'
