### ISSUE TITLE
[TypeScript] - can't set Navbar.Item href attribute

### ISSUE THREAD

**Issue by codebytere** [couds/react-bulma-components#233]
The example used in the [Storybook](https://couds.github.io/react-bulma-components/?path=/story/navbar--default) doesn't work:

<img width="748" alt="Screen Shot 2020-02-24 at 8 10 30 PM" src="https://user-images.githubusercontent.com/2036040/75214247-bd619080-5741-11ea-99d9-29c09e5cd677.png">

Happy to open a PR to fix this if i could get a pointer as to your preferred path forward :)

**Comment by alexandrtovmach** [comment]
It works correctly but for JS, for TS need to update definitions file
details here: https://github.com/couds/react-bulma-components/issues/182

**Comment by couds** [comment]
Closing this. its correctly working on latest @next (V4.0.0-RC.8)
