### ISSUE TITLE
Bulma Components blocking children events

### ISSUE THREAD

**Issue by markdid** [couds/react-bulma-components#236]
Hi, I recently switched a project from bloomer to react-bulma-components.
I have a component built on D3 which utilizes D3's .zoom events to navigate an svg map. When put in a page built using bloomer the map worked just fine. When inserted into a page using react-bulma-components, the .zoom event no longer fires though other events like mouse work just fine. 
When I try to drag around inside my map it moves the whole page instead of the map.

Here is the component
`<Columns.Column>
          <Carrels user={this.props.user} carrels={this.props.carrels.data} />
</Columns.Column>`

`
//Carrels

d3.selectAll(".all").on("zoom", function () {
            console.log(d3.event)

        })

        d3.selectAll(".all").on("mouseover", function () {
            console.log(d3.event)
        })
`

**Comment by MrCreeper1008** [comment]
Hi, I'm not familiar with D3. Can you explain what `.selectAll` does?

**Comment by markdid** [comment]
It selects all svg elements with a given classname. In my case '.all' is the svg group containing the whole map.

**Comment by MrCreeper1008** [comment]
So are your svg elements rendered under the `Carrels` component, which is under `Columns.Column`?

**Comment by markdid** [comment]
Yeah that's correct.

**Comment by MrCreeper1008** [comment]
Thank you. I'll look into it.

**Comment by MrCreeper1008** [comment]
Can you make a minimal repo that can reproduce this issue? Looking into this I don't see why it won't work because `Columns.Column` is just `div` under the hood.

**Comment by markdid** [comment]
Sure, here is a quick and dirty example -> [repo](https://github.com/markdid/react-bulma-map) Note in App.js the shape on top inside the div is draggable while the same component inside Columns is not. I don't think the issue is limited to just the Columns component either.

**Comment by couds** [comment]
Hi @markdid can you please describe the current behavior and the expected behavior, and how to test it?

How to fire the zoom event for example, I downloaded the repo and can zoom in/out with the mouse wheel, but not sure if that the issue you are having.

Thanks!

**Comment by couds** [comment]
Hi @markdid I checked the code and the issue does not seem to be on the react-bulma-component library.

If you change the order on the App.js to 

```jsx
function App() {
  return (
    <div style={{ maxHeight: "300px", maxWidth: '400px' }}>

      <Columns>
        <Columns.Column>
          COLUMN
          <OuterFloorMap>
            <FirstFloor />
          </OuterFloorMap>
        </Columns.Column>
      </Columns>
      <div>
        DIV
        <OuterFloorMap>
          <FirstFloor />
        </OuterFloorMap>
      </div>
    </div>
  );
}
```

The one in the `column` works but the one in the `div` doesn't

**Comment by markdid** [comment]
You're right, i'm trying to re-create the issue now.

**Comment by couds** [comment]
Closing this due inactivity.
