### ISSUE TITLE
"icon" prop required for Icon component but not used with children

### ISSUE THREAD

**Issue by dgilland** [couds/react-bulma-components#24]
In `Icon` component, when `children` are given, the `icon` prop isn't used but `icon` prop is marked as required:

- https://github.com/couds/react-bulma-components/blob/84f8240f4a129bc6d6a73a905e134bff2a6d2f48/src/components/icon/icon.js#L12
- https://github.com/couds/react-bulma-components/blob/84f8240f4a129bc6d6a73a905e134bff2a6d2f48/src/components/icon/icon.js#L50

Personally, I'm using `react-fontawesome` to pass is icon component as a child to the `react-bulma-components` icon component but prop-validation throws an error.

**Comment by couds** [comment]
Hi. thanks for reporting this. 

I will change the icon prop to as an optional prop in the next release.

**Comment by dgilland** [comment]
Sweet! Thanks a lot!

Awesome library btw! :+1:

**Comment by couds** [comment]
@dgilland this should be fixed now in version 1.4.x(Commit a5c99b9664c45c29415e0d3eabc6ef4bde95d7ba)
