### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kennethnym** [couds/react-bulma-components#242]
Using a library that generates documentations from markdown files will make writing documentation much easier and less tedious. Updating documentation will also be easier too. Right now, we are using a full-blown `create-react-app` project just to display a static docs page. It is way too overkill and inefficient imo. cc @couds

**Comment by MrCreeper1008** [comment]
It will also considerably speed up the process of creating the documentation.

**Comment by couds** [comment]
Hi. I understand what you mean but I believe in in using your own library to do the docs https://en.m.wikipedia.org/wiki/Eating_your_own_dog_food

**Comment by MrCreeper1008** [comment]
docz, for example, lets you use your own components for the generated documentation. Is this what you prefer?

**Comment by couds** [comment]
@MrCreeper1008 Docs seem awesome, let's check its make sense to have docz and storybook. because both seem to be quite similar for showing the components.

**Comment by MrCreeper1008** [comment]
I'd say docz does a better job in documenting components because it actually is a documentation generator, whereas storybook is more geared towards component `development`. I think we don't need a storybook anymore if we adopt docz.

**Comment by MrCreeper1008** [comment]
I think docusaurus is a pretty good choice for creating our documentation because it supports custom components and i18n. I created a branch `docs` for all our work on the documentation.

**Comment by couds** [comment]
@MrCreeper1008 Thanks for keeping this on scope! as you suggest let's use docusaurus.I  took a few days off from work to do this. I will take over this and try to have it done asap. I bought react-bulma.io I think It's better than the .dev (Use the same domain as bulma.io =) )

**Comment by MrCreeper1008** [comment]
thanks! currently im still dealing with college stuff (it'll soon be over!) so i havent had time to work on the documentation. if you need help though please let me know. there are a lot to put into documentation so i'll help once i have the time.

**Comment by MrCreeper1008** [comment]
i've already setup docusaurus on `docs` branch so you can start working on documentation directly.

**Comment by Quadrisheriff** [comment]
Hi my name is Sheriff and will like to participate in this project too. Is there anyway we can like distribute the workload between all 3 of us?

**Comment by couds** [comment]
Hello, I just pushed a branch `add-documentation` that deploy [here](http://react-bulma.io). I will continue tomorrow, and start with the docs for each component. After I finish the first component I will push it, after that we can assign components to each of us to create the documentation, the idea will be use the first component as a template for the rest.

**Comment by MrCreeper1008** [comment]
Docusaurus 2 doesn't have i18n support. Are you planning to drop translation support?

**Comment by couds** [comment]
Yes, it does not make sense to use V1 if they are already working on V2.

**Comment by couds** [comment]
@Quadrisheriff Sorry currently I have my hand full. I don't think I will be able to upload the template. I uploaded the scafolding, if you want to start go ahead. the idea is to be a close as possible to the docs of bulma.io. 

Also you can check the getting started in special the part about the `Element` component. I think that is the way we should go.

Thanks!

**Comment by Quadrisheriff** [comment]
I have already started work on the ```elements```, ```layout``` and ```components``` sections, and I should send a PR hopefully before this week's ending.

**Comment by MrCreeper1008** [comment]
@Quadrisheriff thank you for your contribution. just a quick note: i have already documented column > basics and column > sizes, so can you please ignore these two parts when making the pr? makes it easier for me to merge. thanks!

**Comment by MrCreeper1008** [comment]
@Quadrisheriff also please rebase your branch on top of the current `documentation` branch. thank you!

**Comment by timorthi** [comment]
Is #251 the most up-to-date branch for the new docs? Would love to contribute.

**Comment by MrCreeper1008** [comment]
yes, i just merged #266 into `add-documentation` branch.

**Comment by couds** [comment]
Closing this, with V4 we will have a nicely documented library using storybook. Thanks to @kennethnym that did a great job 🎉
