### ISSUE TITLE
Breaking typo in website "Getting started"

### ISSUE THREAD

**Issue by arielaco** [couds/react-bulma-components#248]
https://react-bulma.dev/en/getting-started

The "basic installation" shows the following line:

`import 'react-bulma-components/basic/react-bulma-components.min.css';`

Should be replaced for

`import 'react-bulma-components/dist/react-bulma-components.min.css';`

Otherwise at least with create-react-app, it breaks.

Thank you!

**Comment by MrCreeper1008** [comment]
We're moving away from create-react-app to using docusaurus. Thanks for reporting though!
