### ISSUE TITLE
<Input /> props readonly attribute typo

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#253]
@couds it seems like in input.js:
```
<Element
  ...
  readOnly={readOnly || isStatic}
/>
```
the `readOnly` prop should really be `readonly` because <Element /> is `<input />` under the hood which has an all lowercase `readonly` attribute.  

Same for `<Textarea />` and `<Select />`.

**Comment by MrCreeper1008** [comment]
If this is a bug, I'll make a quick PR to fix this.

**Comment by MrCreeper1008** [comment]
Some props of the input components can be removed because they are the same as their html attributes, like `disabled` and `placeholder`.

**Comment by couds** [comment]
Hi @MrCreeper1008 on read the `readonly` its camelcase https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes.

Also the duplicate proptypes are there because this enable some Bulma behavior. I think we should keep it.

**Comment by MrCreeper1008** [comment]
Understood. Thanks.
