### ISSUE TITLE
[VOTE] Change Bulma dependency to peerDependenc. and remove the import of the styles from this library

### ISSUE THREAD

**Issue by couds** [couds/react-bulma-components#258]
Hi. I want to know what all of you think about removing the advanced configuration.

The Idea its to move Bulma to a peerDependency use this library only as a helper to add the bulma classes (Instead of also adding the css).

This is because all the issues are about Typescript or the advanced installation (Overwrite the variables)

Almost all frameworks now supports saas out of the box and it will be easier to the developers to follow the instructions of their frameworks to configure/modify their saas importation.

Obviously this will be a breaking change and will be done as a major release.

I will leave this post at least for a Month so all can vote

https://doodle.com/poll/mqqpxwkzm6nnrs3s

**Comment by MrCreeper1008** [comment]
Agreed. However, we need to have a version table that shows which bulma version should be used with which version of `react-bulma-components`, since sometimes we need to introduce new code to support new features in bulma.

**Comment by couds** [comment]
Not too many people voted, but all seem's to agree to this. so We sill go forward and change bulma to be a peerDependency. and remove all the sass import from this library.
