### ISSUE TITLE
Panel prop-type "colors" wrong?

### ISSUE THREAD

**Issue by verheyenkoen** [couds/react-bulma-components#259]
Not sure but I guess [this prop-type](https://github.com/couds/react-bulma-components/blob/e130e2e1182423151d54b3f024fcbf04885a3a2f/src/components/panel/panel.js#L35) should be named "color", not "colors"?

Anyway, I'm getting a warning on this:

> Failed prop type: Panel: prop type `colors` is invalid; it must be a function, usually from the `prop-types` package, but received `object`.

Even though I don't set that attribute/property.

**Comment by MrCreeper1008** [comment]
Hmm yes it should be named color not colors, but you shouldn’t be getting that warning anyway if you gave the correct value. Can you show me your code?
