### ISSUE TITLE
Cannot select a tab in the storybook

### ISSUE THREAD

**Issue by sksamuel** [couds/react-bulma-components#269]
It just stays on the same tab all the time.

**Comment by couds** [comment]
Hi @sksamuel . Yes the storybook for tabs do not have any logic just show how the set the active tab (on the code) but now how to handle the state, that's our of the scope of the library

**Comment by sksamuel** [comment]
Ok thanks. I was confused on how to react (excuse the pun) to a change in
state. Most other react libraries I've used accept some kind of handler
that is invoked when a tab changes.
I'm not an experienced react user.
What I did in the end was add an onclick handler to each of the tabs, but
that's a lot of duplication.
