### ISSUE TITLE
Overriding variables with Gatsby

### ISSUE THREAD

**Issue by alexpchin** [couds/react-bulma-components#270]
Hello, I've been stuck on a problem for the last day. 

I have a `_variables.scss` file which I have included at the root of my src directory in Gatsby. I have setup my `gatsby-plugin-sass` as follows:

```js
{
      resolve: `gatsby-plugin-sass`,
      options: {
        includePaths: [`${__dirname}/src`],
      },
},
```

I also have a main `styles.scss` file located at `src/assets/scss/styles.scss`. To get the bulma styling working I need to import: `@import "~react-bulma-components/src/index.sass";` at the top of this file.

I think include this file at the top of the `gatsby-browser.js` file:

```js
import "./src/assets/scss/styles.scss"
```

However, changes to the variables in `_variables.sass` do not seem to be applied:

```
$family-sans-serif: "Arial", sans-serif !default
$danger: 'yellow'
```

Am I missing something? I think I have followed the documentation well.

**Comment by MrCreeper1008** [comment]
I have no experience in Gatsby, but have you tried directly pointing to your scss folder for the `includePaths` option?

**Comment by alexpchin** [comment]
@MrCreeper1008 Hi, yes I have also tried this with no luck.

**Comment by alexpchin** [comment]
This would be fixed with the proposal to remove styles so that Gatsby could manage the order of the styles better.

**Comment by couds** [comment]
In V4 we are dropping the sass generation and leave it to the developer to set up bulma on the project.
