### ISSUE TITLE
Advanced usage does not work with CRA

### ISSUE THREAD

**Issue by deckardd** [couds/react-bulma-components#272]
CRA will only import valid JS. It does not support importing/compiling JSX from external libraries. (See their statement [here](https://github.com/facebook/create-react-app/issues/5103#issuecomment-425459196).)

So, when attempting to do the recommended advanced react-bulma-components usage pattern, CRA fails with a syntax error.

```
./node_modules/react-bulma-components/src/components/button/button.js
SyntaxError: Unexpected token (58:4)

  56 | 
  57 |   return (
> 58 |     <Element
     |     ^
  59 |       tabIndex={disabled ? -1 : 0}
  60 |       renderAs={renderAs}
  61 |       {...props}
```

Is there any current suggested work around and/or plans to support custom variables in a different way in the future?

**Comment by couds** [comment]
Hi @deckardd you are importing from `src` please import from `react-bulma-components/lib` instead

**Comment by deckardd** [comment]
Ahh, thank you! I was mixing up the documentation for CRA and Next.js. Thanks for the fast response! You saved me a lot of time.
