### ISSUE TITLE
Failed to compile CRA

### ISSUE THREAD

**Issue by semivori** [couds/react-bulma-components#281]
`npm run start` gives error:

> SyntaxError: myApp\node_modules\react-bulma-components\src\components\box\box.js: Support for the experimental syntax 'jsx' isn't currently enabled (9:3):

```
   8 | const Box = ({ children, className, ...props }) => (
>  9 |   <Element {...props} className={classnames('box', className)}>
     |   ^
  10 |     {children}
  11 |   </Element>
  12 | );
```

> Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.

**Versions**
- `react-bulma-components:`: ^3.4.0
- `bulma` ^0.9.0:
- `react`: ^16.13.1
- `create-react-app`: 3.4.1

**Comment by couds** [comment]
Hi @semivori 

Can you change the import from `src` to `lib`

```
import Box from 'react-bulma-components\lib\components\box'
```

**Comment by semivori** [comment]
@couds it gives next error
```
./node_modules/react-bulma-components/lib/components/box/box.sass (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./node_modules/react-bulma-components/lib/components/box/box.sass)
SassError: File to import not found or unreadable: _variables.sass.
        on line 3 of node_modules/react-bulma-components/lib/components/utils.sass
        from line 1 of D:\Projects\tman\node_modules\react-bulma-components\lib\components\box\box.sass
>> @import "_variables.sass";
```

**Comment by couds** [comment]
Did you follow the instructions here?

https://github.com/couds/react-bulma-components#cra

**Comment by semivori** [comment]
@couds I have no `jsconfig.json` file in the project. Can you please tell me where it should be? And what should it contain besides "compilerOptions"?

**Comment by MrCreeper1008** [comment]
@semivori it should be at the root of your project.

**Comment by jameswinston58** [comment]
I've had a similar problem all day with this. I've followed all the instructions on the advanced configuration.

**Comment by couds** [comment]
@semivori I'm closing this, if you are still having this issue feel free to reopen it =)
