### ISSUE TITLE
[HELP] Clean up the InputFile component via JavaScript

### ISSUE THREAD

**Issue by Ziomioslaw** [couds/react-bulma-components#282]
Hi

How you clear out the selected file for InputFile component using Java Script code?
Without form wrapping of the component.

For simple HTML I can manipulate of `value` attribute: [example of clearing out the input[type=file]](https://codesandbox.io/s/black-voice-mkrmq?file=/src/App.js). But it's not working for InputFile from react-bulma-components.

I have look into [code](https://github.com/couds/react-bulma-components/blob/43ce71c720bf3b0eb6cf61a47a6a4b2b23eec737/src/components/form/components/input-file.js), but it didn't bring me any idea.

The best, when it could be achieve by state manipulation, because it will feat to my [project](https://github.com/Ziomioslaw/congenial-broccoli/blob/master/src/components/AddCategoryItem.js#L56).

I will glad for any help.
Best regards

**Comment by MrCreeper1008** [comment]
Try passing `value` via the `inputProp` prop and modify its value.

**Comment by Ziomioslaw** [comment]
Hi, thanks for replaying, but this is not working.
I guess, because InputFile is compose not only with File, but also label, and span etc...

**Comment by MrCreeper1008** [comment]
This is weird. I'll see what I can do. If a patch is needed it'll be pushed in v4. Thank you for filing this issue.

**Comment by Ziomioslaw** [comment]
Thanks, I looking forward to it :)

**Comment by couds** [comment]
Actually we will need to change this component to a controlled component and remove the inner state.

Probable add the label as a prop instead of in the state.  I will create a PR tomorrow

**Comment by MrCreeper1008** [comment]
We should probably make other components stateless as well if possible.

**Comment by couds** [comment]
I just released a new version of next with all the pending changes. (Special thanks to @MrCreeper1008 without him I dont think I could be able to continue support this project) in this version the input-file its now a controlled component. so you can easy use the `filename` prop to setup and clear the value displayed on the html and the `value` props to the actual value of the input (if you are accessing it outside react for any reason)

**Comment by MrCreeper1008** [comment]
@couds I renamed the `value` prop to `files` prop to avoid confusion because it affects the `files` attribute of the actual `<input>`.
