### ISSUE TITLE
CSS conflicts with Docusaurus and Bulma

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#285]
**Describe the bug**
When importing Bulma css in Docusaurus, JSX code examples look weird because JSX elements have class name `tag` which is a valid class in Bulma.

**To Reproduce**
1. Import Bulma CSS in docuraurus

**Screenshots**
![Screen Shot 2020-11-12 at 3 05 50 PM](https://user-images.githubusercontent.com/19359984/98956953-8feb8b80-24f8-11eb-80e5-f0590f40d275.png)

**Expected behavior**
JSX examples should be rendered correctly

**Additional context**
Right now I have zero idea how to fix this issue. The only option I can think if is migrate to storybook documentation.

cc @couds

**Comment by MrCreeper1008** [comment]
I'm migrating to [@storybook/addon-docs](https://www.npmjs.com/package/@storybook/addon-docs), since it integrates with storybook better.

**Comment by couds** [comment]
Let's drop docusaurus then, its a shame but this does not seem easy to fix.
