### ISSUE TITLE
Update on v4.0

### ISSUE THREAD

**Issue by kennethnym** [couds/react-bulma-components#287]
These past couple months I (and I guess also @couds) are occupied with personal stuff, and so we weren't able to put a lot time into pushing v4. Starting this week, I'll start getting v4 back on track and I hope @couds can do a beta release on it, so we can iron out all the bugs before making it stable.

My apologies for the delay.

**Comment by MrCreeper1008** [comment]
Sneak peeks of the storybook docs I have been working on! Not only are components nicely documented, you can also play around with them using storybook controls. Looking forward to publish this.

<img width="1552" alt="Screen Shot 2020-12-17 at 2 15 25 AM" src="https://user-images.githubusercontent.com/19359984/102435112-f68b2a00-400d-11eb-8540-7c2aaf8ac31a.png">
<img width="1552" alt="Screen Shot 2020-12-17 at 2 16 57 AM" src="https://user-images.githubusercontent.com/19359984/102435115-f7bc5700-400d-11eb-95c6-033692353f02.png">
