### ISSUE TITLE
[HELP] TypeScript types

### ISSUE THREAD

**Issue by FunctionDJ** [couds/react-bulma-components#296]
How can i get type definitions for any recent version of this library? I would really like to have IDE-support for validating my code as i program, not having to hit up the docs all the time. Also i'd like to switch to strict mode.

**Comment by MrCreeper1008** [comment]
typescript def is available on v4. You can try it out by installing the `next` branch of this repo.

**Comment by FunctionDJ** [comment]
Thank you =)
