### ISSUE TITLE
[HELP] Using <Button> as child of Next.js <Link> (refs)

### ISSUE THREAD

**Issue by FunctionDJ** [couds/react-bulma-components#300]
I'd like to use a `<Button>` component as a child of a Next.js `<Link>` component, but i get an error that function components can't have refs.
I tried wrapping the button in `React.forwardRef()`, but i think i'm doing this wrong.

My code (only `<Link>` is coming from Next.js):
```tsx
<Link href="/download">
  <Button color="link" className="has-text-weight-bold">
    <Icon>
      <span className="fas fa-download"/>
    </Icon>
    <span>Download</span>
  </Button>
</Link>
```

**Comment by couds** [comment]
Hello @FunctionDJ  for this you can use the prop RenderAs like this

```javascript
<Button renderAs={Link} href="/download">
  Download
</Button>
```

**Comment by FunctionDJ** [comment]
Thank you so much! Why didn't that occur to me lol

**Comment by FunctionDJ** [comment]
Actually the `<Link>` component doesn't support "being" a button and it gets styled like an anchor instead of a button.
The correct approach is the following, as i found out from [this page](https://dev.to/ivandotv/using-next-js-link-component-with-material-ui-buttons-and-menu-items-3m6a):
```jsx
<Link href="/download" passHref>
  <Button>
    helo world
  </Button>
</Link>
```
