### ISSUE TITLE
Release v4 beta

### ISSUE THREAD

**Issue by kennethnym** [couds/react-bulma-components#301]
@couds wdyt about doing a beta v4 release so we can discover and iron out bugs and perhaps get some feedback from our users?

**Comment by davepwsmith** [comment]
Hi, not sure if this should be here or on #262 or #287... But:

The Modal has some sort of issue with types: 

````JSX
const PhotoModal: React.FC<PhotoModalProps> = ({ open, setOpen, url }) => {
  return (
    <Modal
      show={open}
      onClose={() => setOpen(false)}
    >
      <Modal.Content>

      <Image
        src={url}
        onClick={() => {
          setOpen(false)
        }}
        style={galleryImage}
        />
        </Modal.Content>
    </Modal>
  )
}
````


````
Type '{ children: Element; show: boolean; onClose: () => void; }' is not assignable to type 'IntrinsicAttributes & ModalProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ModalProps'.
````

**Comment by MrCreeper1008** [comment]
Thanks for reporting, will look into it.

**Comment by MrCreeper1008** [comment]
@davepwsmith your issue is transferred to #302

**Comment by pentolbakso** [comment]
Hi, just upgraded to v4.0.0-1 .. was smooth except for missing List component. But that is easy fix. Great jobs guys!

**Comment by MrCreeper1008** [comment]
We removed the List component since it is removed in bulma v9

**Comment by couds** [comment]
Closing this to have only one issue related to v4 release
