### ISSUE TITLE
Modal TypeScript type does not allow children

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#302]
**Describe the bug**
When trying to add children to `Modal`, a TypeScript error is reported saying children prop does not exist.

**To Reproduce**
1. Add children to `Modal`

**Expected behavior**
It should allow children components.

**Screenshots**

**Versions**
- `react-bulma-components:`: v4
- `bulma`: 0.9.x

**Additional context**
Transferred from #301 reported by @davepwsmith

cc @davepwsmith

**Comment by MrCreeper1008** [comment]
@datepwsmith please let me know if this (f2e1a0a98d44e8dca0a6fc0cdcced9d9dac6f7f1) has fixed your issue. You can pull the change by installing `next` branch of this library.

**Comment by davepwsmith** [comment]
I'm afraid it does not - however, the following does: 

```ts

export type BulmaComponentWithoutModifiers<TProps> = (
  props: TProps,
) => React.ReactElement;

export const Modal: BulmaComponentWithoutModifiers<ModalProps> & {
  Content: BulmaComponent<{}, 'div'>;
  Card: BulmaComponent<{}, 'div'> & {
    Head: BulmaComponent<ModalCardHeadProps, 'header'>;
    Body: BulmaComponent<{}, 'section'>;
    Footer: BulmaComponent<{}, 'footer'>;
    Title: BulmaComponent<{}, 'p'>;
  };
};

```

**Comment by MrCreeper1008** [comment]
This is very odd - `BulmaComponentWithoutModifiers` has a type signature of:

```ts
export type BulmaComponentWithoutModifiers<TProps> = (props: TProps) => React.ReactElement;
```

in f2e1a0a98d44e8dca0a6fc0cdcced9d9dac6f7f1 I just removed the alias and directly put the signature in place:

![Screen Shot 2021-02-18 at 17 39 44](https://user-images.githubusercontent.com/19359984/108397825-4b1a7380-7210-11eb-92f9-e01d5c03b01c.png)

I don't see why it wouldn't work :/ Let me try on my machine and report back. Thank you for the detailed response.

**Comment by davepwsmith** [comment]
I am not an expert, I will admit, but I think that export type is different to export const more fundamentally than just aliasing.

**Comment by MrCreeper1008** [comment]
I figured the problem out, its because I forgot to put parenthesis around the function signature so the `& ...` got interpreted as the return type of the function instead.
