### ISSUE TITLE
Missing `m` property on <Columns>

### ISSUE THREAD

**Issue by martinlehoux** [couds/react-bulma-components#305]
**Describe the bug**
This is a TypeScript issue.
While using <Colmuns>, I was able to use `mx={}` and `my={}`, but I couldn't find `m={}` autocomplete.
I didn't test other components, but I guess they all have the same issue. I will check ASAP and complete this issue.

**Expected behavior**
This helper should be available, as written there : https://bulma.io/documentation/helpers/spacing-helpers/#list-of-all-spacing-helpers

**Versions**
- `react-bulma-components:`: 4.0.0-1

**Comment by MrCreeper1008** [comment]
will fix asap. thanks for letting me know.

**Comment by MrCreeper1008** [comment]
should be fixed in f69ae720dee79437e409dbb736ce432c6b04318a, you can test it out by installing the `next` branch directly. need to wait for @couds to release the next patch.

**Comment by couds** [comment]
Just published 4.0.0-2 on next tag. let me know if the issue its solved.

Thanks!

**Comment by couds** [comment]
Closing this. was fixed on 4.0.0-2
