### ISSUE TITLE
SassError: media query expression must begin with '(' [HELP]

### ISSUE THREAD

**Issue by kumardennis** [couds/react-bulma-components#312]
SassError: media query expression must begin with '('
        on line 2 of node_modules/react-bulma-components/lib/components/button/button.sass
>> @import '~bulma/sass/elements/button.sass'

is the error I get when I compile a gatsby project.
How can I get by ? do I need to edit node_modules file ?

**Comment by couds** [comment]
Question: do you enabled sass on gatsby? (And followed the docs on the readme)

Also maybe you want to checkout the v4. It's in RC.1 you can install it with `npm I react-bulma-components@next` take into account that in this version you need to import the bulma styles yourself

**Comment by couds** [comment]
@kumardennis can you share a repository to replicate this issue?

Also if possible I recommend to move to the v4.

**Comment by couds** [comment]
Closing this due inactivity.

Please reopen this task if you still had the issue and add the step to replicate the error.

Thanks
