### ISSUE TITLE
v4: NavbarProps size is mandatory and only has one value

### ISSUE THREAD

**Issue by davepwsmith** [couds/react-bulma-components#313]
Is this supposed to be a mandatory prop? Seems especially odd since there's only one allowed value.

```typescript
interface NavbarProps {
  transparent?: boolean;
  fixed?: 'top' | 'bottom';
  size: 'large';
  color?: Color;
  active?: boolean;
}
```

_Originally posted by @davepwsmith in https://github.com/couds/react-bulma-components/pull/265#r611058911_

**Comment by couds** [comment]
Thanks for reporting this. nice catch!
