### ISSUE TITLE
v4: RenderAs type errors for GatsbyLink (e.g. - but I suspect any customized component type would fail)

### ISSUE THREAD

**Issue by davepwsmith** [couds/react-bulma-components#314]
![image](https://user-images.githubusercontent.com/1024707/114275961-73f30400-9a1c-11eb-9dd1-3924dfc27b5e.png)

Having the type as <never> seems to have a dual effect of expecting multiple children, and also preventing other typed components being used for renderAs. 

Changing 
`export type RenderAsComponent = string | React.ComponentType<never>`
to 
`export type RenderAsComponent = string | React.ComponentType`
or 
`export type RenderAsComponent = string | React.ComponentType<any>`

Both seem to fix the problem, but not sure what the side effects would be. 

Are you looking to explicitly prevent people from using other components in renderAs? Because that will basically prevent people from using this with Gatsby I think?

**Comment by davepwsmith** [comment]
I suspect that what is actually wanted here is [`React.ElementType`](https://flow.org/en/docs/react/types/#toc-react-elementtype)? This would allow to render as all components, and also as basic intrinsic HTML types such as <a> and <div>. Happy to PR this if that's the case.

**Comment by couds** [comment]
@davepwsmith Yes please open the PR =) 

Thanks
