### ISSUE TITLE
Allow renderAs to receive another React-Bulma-Components Component as a value

### ISSUE THREAD

**Issue by couds** [couds/react-bulma-components#315]
Currently the renderAs prop do not allow to compose using Components from the library itself

**To Reproduce**

In a TS project add

```jsx
import React from 'react';
import { Content, Notification } from 'react-bulma-components';

function App() {
  return <Content renderAs={Notification} color="success">Any data</Content>;
}

```

 See errors

![image](https://user-images.githubusercontent.com/2903371/114279735-6e0a1c80-9a36-11eb-8c18-69c21cadacad.png)

![image](https://user-images.githubusercontent.com/2903371/114279762-88dc9100-9a36-11eb-9b53-31bcf9a3166b.png)

**Expected behavior**
- No errors
- If possible autodetect the props as with `html` 

**Versions**
- `react-bulma-components:`: 4.0.0-RC.1
- `bulma`: 0.9.2
- `react`: 17
- Browser: (e.g. Firefox version 67): NA

**Comment by kennethnym** [comment]
will fix asap.

**Comment by couds** [comment]
@kennethnym Thanks!

**Comment by kennethnym** [comment]
seems like this is fixed. closing
