### ISSUE TITLE
[HELP] How to use icon-text property ? 

### ISSUE THREAD

**Issue by Tstassin** [couds/react-bulma-components#333]
Hello,

Using react-bulma-components v4.0.3 (and first of all thank you for the amazing work)

How am i supposed to use the [icon-text](https://bulma.io/documentation/elements/icon/#icon-text) property from Bulma 0.9.2 ?
Looking into the repo I found references to a `text` boolean prop for the icon component, but I can't seem to make it work, and I find it a strange way of doing it 

```
<Icon text>
  <Icon>..</Icon>
  <Element>..</Element>
</Icon> 
```

Using it this way outputs both `icon`and `icon-text` classnames to the parent Icon element, which renders buggy...
From my understanding the parent Component should be of type span/Element, not Icon..

**Comment by kennethnym** [comment]
I will transfer this issue to discussion. If it turns out it's a bug, I will open another issue.
