### ISSUE TITLE
[HELP] Usage with next.js link in navbar?

### ISSUE THREAD

**Issue by Brawl345** [couds/react-bulma-components#344]
I read https://github.com/couds/react-bulma-components/issues/300 and https://github.com/vercel/next.js/issues/7915 I still don't know if it's possible without errors to use Next.js `link` (https://nextjs.org/docs/api-reference/next/link) with Bulma. When I use it like this:

```jsx
    <Navbar color="dark">
      <Navbar.Brand>
        <Link href="/" passHref>
          <Navbar.Item>
            Example
          </Navbar.Item>
        </Link>
        <Navbar.Burger />
      </Navbar.Brand>

      <Navbar.Menu>
        <Navbar.Container>
          <Link href="/" passHref>
            <Navbar.Item active={router.pathname === '/'}>
              Home
            </Navbar.Item>
          </Link>
        </Navbar.Container>
      </Navbar.Menu>
    </Navbar>
```

I get: `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

I also tried `forwardRef` like here: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-function-component but it doesn't seem to work :/

Using `renderAs` is also not possible because it ends up as an unstyled anchor tag. I think this is something that has to be fixed on the Next.js side but they don't seem t be willing to fix it and it works with react-bootstrap... Do you have any idea? Thank you!

**Comment by couds** [comment]
Hi @Brawl345 Maybe you can try something like this

```jsx
const CustomItem = React.forwardRef((props, ref) {
  return (
    <Navbar.Item {...props} domRef={ref }/>
  );
});
```

I didn't test it but I think this should work.

Also do you know why the `renderAs` cause the anchor to lose the styling? in theory should work

**Comment by Brawl345** [comment]
Thank you very much :D!! That did the trick! You just forgot the `=>` before the opening `{` for the CustomItem, so:

```jsx
  const CustomItem = forwardRef((props, ref) => (
    <Navbar.Item {...props} domRef={ref} />
  ));
```

----
> Also do you know why the renderAs cause the anchor to lose the styling? in theory should work

Good question... I tried this:

```jsx
<Navbar.Item renderAs={Link} active={router.pathname === '/'} href="/">
  Home
</Navbar.Item>
```

and ended up with:

```html
<div class="navbar-start"><a href="/">Home</a></div>
```

(note the missing `navbar-item` class).

**Comment by couds** [comment]
After reading the next documentation seems that next Link do not pass the `className` internally.

**Comment by faeb187** [comment]
looks like the only superpower of Navbar.Item is the 'navbar-item' class?
`<Link href="/" className="navbar-item">done</Link>`
