### ISSUE TITLE
Tree Shaking Not working in Gatsby

### ISSUE THREAD

**Issue by rotexhawk** [couds/react-bulma-components#345]
My site slowed down after updating to the latest react-bulma and on bundle analysis I noticed that the tree shaking feature is not working. I am using this plugin in gatsby. 

<img width="973" alt="Screen Shot 2021-06-08 at 11 11 50 PM" src="https://user-images.githubusercontent.com/12015105/121287268-37724600-c8af-11eb-9170-94474119513d.png">

**Comment by couds** [comment]
Hi @rotexhawk can you share your configuration?and if possible a small repo with a reproducible example

Without more information it's quite difficult to understand what is happening

**Comment by rotexhawk** [comment]
Hello @couds, thanks for the quick reply. I setup a bare bone repo here. https://github.com/rotexhawk/jameygittings. All you have to do is `npm install` and `npm run build`. 

Thanks

**Comment by couds** [comment]
Hi @rotexhawk after checking [this issue](https://github.com/gatsbyjs/gatsby/issues/7581#issuecomment-415509521) in Gatsby, seems that the tree shaking only works on ES6 Modules, and the default export for this library its commonjs.

We also have es6 export, you need to change the import like this

```jsx
// CommonJS (Default)
import { Content, Footer, Container } from "react-bulma-components";

// ES6
import { Content, Footer, Container } from "react-bulma-components/esm";
```

With this the tree shaking works 

![image](https://user-images.githubusercontent.com/2903371/121744290-f7a39c80-cb02-11eb-9ccf-4cd4d32bca98.png)

**Comment by rotexhawk** [comment]
Great. Thanks for the update. This works :)
