### ISSUE TITLE
Form checkboxes 'checked' prop not working

### ISSUE THREAD

**Issue by Tstassin** [couds/react-bulma-components#346]
It seems like Checkbox component doesn't handle correctly the 'checked' prop.

Please see : 
https://codesandbox.io/s/stupefied-kepler-b3iee?file=/src/App.js

**Comment by kennethnym** [comment]
For some reason it's working for me locally in storybook. I'll look into this.

**Comment by couds** [comment]
Hi @Tstassin @kennethnym The issue was a faulty build. I republished `v4.0.7`, now should work properly

See 
https://codesandbox.io/s/keen-ride-ytdnw?file=/src/App.js
