### ISSUE TITLE
Example list of icons

### ISSUE THREAD

**Issue by verheyenkoen** [couds/react-bulma-components#36]
Is there a list of available icons in the `react-bulma-componentsregular` font?

**Comment by couds** [comment]
Helli @verheyenkoen for now the font only have the 2 icons showed on the storybook, and I will probable leave only angle-down because its used by the dropdown and remove the other icon

**Comment by couds** [comment]
Hi @kennedybaird the idea behind this its to enable the developer to use the icons they want. in reality this Icon component what it does its to prevent the "page jump" meanwhile the icon is loaded. From the Bulma.io docs

```
The icon element is a container for any type of icon font. Because the icons can take a few seconds to load, and because you want control over the space the icons will take, you can use the icon class as a reliable square container that will prevent the page to "jump" on page load.
```

**Comment by winfredkqin** [comment]
@couds So can you add a tip on README saying something like: by default, only two icons included? It did confuse me for a few hours on this.
