### ISSUE TITLE
No Control, Field, and other components included in the Storybook

### ISSUE THREAD

**Issue by jdmg94** [couds/react-bulma-components#37]
The Storybook depicts some components that don't exist within this repo, they're really simple components like Field, Control, Label and others that are depicted mainly in the form examples. 
If you try to follow the documentation as is it won't work because the aforementioned components just don't exist within the repo.

![screen shot 2018-06-02 at 8 40 37 am](https://user-images.githubusercontent.com/4754734/40877629-630e9652-6641-11e8-869a-59a2828a8005.png)

**Comment by couds** [comment]
Hi @jdmg94 all this component are bundled inside the Form component and can be imported as named import [here](https://github.com/couds/react-bulma-components/blob/master/src/components/form/form.story.js) you can see the source code of the storybook

**Comment by jdmg94** [comment]
Thanks for the clarification @couds  I see the components now
