### ISSUE TITLE
Warning: Unsafe legacy lifecycles

### ISSUE THREAD

**Issue by Max-Zviagintsev** [couds/react-bulma-components#39]
Getting this error in a console:

> Warning: Unsafe legacy lifecycles will not be called for components using new component APIs. Navbar uses getDerivedStateFromProps() but also contains the following legacy lifecycles: componentWillReceiveProps The above lifecycles should be removed.

**Comment by couds** [comment]
Hi @Max-Zviagintsev Yes for now this is intended (for now), see https://github.com/couds/react-bulma-components/issues/25
