### ISSUE TITLE
ImageProps error when compiling typescript project.

### ISSUE THREAD

**Issue by Dashron** [couds/react-bulma-components#400]
I've got a setup where I'm trying to use this project for server side rendering, just using the react-jsx output of the typescript compiler. When I run tsc I get this error.

```
error TS2749: 'ImageProps' refers to a value, but is being used as a type here. Did you mean 'typeof ImageProps'?

Image: BulmaComponent<ImageProps, 'figure'>;
```

I poked around and it looks like [this line](https://github.com/couds/react-bulma-components/blob/82d13fc9d8c9ffee46c21318450127b92cbf128e/src/components/card/index.d.ts#L2) is incorrect, because the [referenced file](https://github.com/couds/react-bulma-components/blob/master/src/components/image/index.d.ts#L3) doesn't expose `ImageProps`. 

I'm happy to throw together a quick PR if you'd like.

**Comment by Dashron** [comment]
Ignore me, I just saw the discussion in the other issues! I should have taken a little longer to look for them.

**Comment by kennethnym** [comment]
No worries, glad you found a solution.
