### ISSUE TITLE
Content is not working with dynamic content 

### ISSUE THREAD

**Issue by dipeshparashar** [couds/react-bulma-components#401]
I am using v4.0.2 . Trying to use Content component with dynamic content. It does not render html elements. Let me know if i am doing anything wrong here. How can i resolve this ?

```
 <Message >
       <Content >
            {n.message}
       </Content>
 </Message>
```

Rendered UI 

![Bulma-Content-Dynamic](https://user-images.githubusercontent.com/8472277/184882497-c3b3c4ef-939b-4929-83a3-1196573f695f.png)

**Comment by couds** [comment]
Hi @diploidal this is how react works, if you want to render html that is coming from a variable you need to use `dangerouslysetinnerhtml` https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by diploidal** [comment]
Hey,
I don't want to bother You @couds but You've tagged wrong person. 😃 

It is not a huge problem but by fixing tagged user You'll be sure that the author of this issue is notified. 😃
