### ISSUE TITLE
How to use it with React FontAwesome component?

### ISSUE THREAD

**Issue by koddr** [couds/react-bulma-components#43]
Hello.

> Would be great to replace icons with [React FontAwesome](https://github.com/FortAwesome/react-fontawesome) component. 

I have no idea what is the `rbc rbc-*` icons do you use into React Bulma component, for example, [Dropdown](https://couds.github.io/react-bulma-components/?selectedKind=Dropdown&selectedStory=Default&full=0&addons=0&stories=1&panelRight=0) component? But...

Code is:

```jsx
import React, { Component } from 'react';

import Hero from 'react-bulma-components/lib/components/hero';
import Dropdown from 'react-bulma-components/lib/components/dropdown';

class SliderHero extends Component {
  render () {
    return (
      <Hero size="fullheight" color="link">
        <Hero.Body>
          <Dropdown hoverable>
            <Dropdown.Item value="item">
              Dropdown item
            </Dropdown.Item>
            <Dropdown.Item value="other">
              Other Dropdown item
            </Dropdown.Item>
            <Dropdown.Item value="active">
              Active Dropdown item
            </Dropdown.Item>
            <Dropdown.Item value="other 2">
              Other Dropdown item
            </Dropdown.Item>
            <Dropdown.Divider/>
            <Dropdown.Item value="divider">
              With divider
            </Dropdown.Item>
          </Dropdown>
        </Hero.Body>
      </Hero>
    );
  }
}

export default SliderHero;
```

HTML is:

```html
<section className="hero is-link is-fullheight">
  <div className="hero-body">
    <div className="dropdown is-hoverable">
      <div className="dropdown-trigger" role="presentation">
        <a tabIndex="0" className="button">
          <span>Dropdown item</span>
          <span className="icon is-small"><i className="rbc rbc-angle-down"></i></span>
        </a>
      </div>
      <div className="dropdown-menu" id="dropdown-menu" role="menu">
        <div className="dropdown-content">
          <div title="item" role="presentation" className="dropdown-item">Dropdown item</div>
          <div title="other" role="presentation" className="dropdown-item">Other Dropdown item</div>
          <div title="active" role="presentation" className="dropdown-item">Active Dropdown item</div>
          <div title="other 2" role="presentation" className="dropdown-item">Other Dropdown item</div>
          <hr className="dropdown-divider">
          <div title="divider" role="presentation" className="dropdown-item">With divider</div>
        </div>
      </div>
    </div>
  </div>
</section>
```

And output is:

<img width="100%" alt="screen shot 2018-06-16 at 20 03 05" src="https://user-images.githubusercontent.com/11155743/41500783-d42aec5e-71a0-11e8-88b1-0dac7610ddb0.png">

How to solve this OR use FontAwesome instead strange `rbc-*` icons? 
Please help me.

**Comment by couds** [comment]
Hi @koddr Can you show me your webpack configuration and how are you importing the Dropdown component? (I was not able to replicate the missing icon).

About the icon set I only include the angle-down there are no icons inside the library that mean to be used externally, the idea of the Icon component its to be composed to generate the Icons you need your your project and avoid to be attached to a icon library.

If you want to use React-bulma-components with FA you can do it (see this example code https://github.com/couds/react-bulma-components-example/tree/font-awesome to get an idea).

btw: the class **rbc-*** its from **R**eact-**B**ulma-**C**omponents =)

**Comment by koddr** [comment]
@couds OMG, I try to understand "what's `rbc-*`", but never look to it by this side :)

I use default `create-react-app` for show this code.

**Comment by couds** [comment]
Hello. Sure I will try to write something this night. Meanwhile You can take a look to the Icon folder inside src/components. 

The main idea it's to wrap the Icon component (in this case the FA icon we think the Icon that comes in RBC. Like bulma.io my component only create the space for th icon instead of render the actual icon. 

Let my know if this help

**Comment by koddr** [comment]
@couds not yet, but hope to wait for update in your docs 👍

**Comment by LaRuaNa** [comment]
Honestly i also didn't understand exactly how to use Icon component but this was my solution:

```
import FontAwesomeIcon from '@fortawesome/react-fontawesome';
import Icon from 'react-bulma-components/lib/components/icon';

<Icon>
            <FontAwesomeIcon icon={faUserPlus} />
</Icon>
```

**Comment by couds** [comment]
That's it. The Icon component only prepare the space for the icon

**Comment by LaRuaNa** [comment]
Ah i see. Then can update the docs that way

**Comment by koddr** [comment]
Okay, it's very helpful 👍 When you updates Storybook?

**Comment by LaRuaNa** [comment]
It's updated already, probably @couds needs to deploy it :)

**Comment by couds** [comment]
Done =)

**Comment by jonalv** [comment]
I am having this exact same issue. The icon is not showing. First I thought I needed to import the icons component but that didn't help either. I see in my html that the dropdown should have an icon `rbc-angle-down` but it doesn't show up. Why not?

**Comment by couds** [comment]
Hi @jonalv can you give me an example code where do you have this issue (if you can prepare a small repo or something  to be able to debug would be a great help)

Thanks

**Comment by jonalv** [comment]
Oki, my example can be found here: https://github.com/jonalv/bulma-react-example

**Comment by julianjohannesen** [comment]
Thanks so much @couds and @LaRuaNa! I was struggling with this. Should have googled much earlier!

**Comment by yuniel777** [comment]
Hi, i still dont understand how icon could be displayed.
Some help plz ^^ 

`import React, { Component } from 'react';
import { withTranslation } from 'react-i18next';
import { Dropdown } from 'react-bulma-components';

class SwitchLanguage extends Component{

    constructor(){
        super();
        this.state = {
          languages:  [],
          selected: 'active',
          visualising: undefined,
          value: "en-US",
          class:"is-not-up",
        }
      }
    
      changeVisualising = visualising => {
        this.setState({ visualising });
        let newlang = visualising;
        this.setState(prevState => ({ value: newlang }));
        this.props.i18n.changeLanguage(newlang);
      };
    
       componentDidMount () {
    
        fetch('https:///ws.atonline.com/_rest/Language:local')
        .then(data => {
          return data.json();
        }).then(data => {
          let languages = data.data.map((lang) => (
              <Dropdown.Item hoverable="true" value={lang.Language__} key={lang.Language__}>
                {lang.Local_Name}
              </Dropdown.Item>
            )
          )
          this.setState({languages:languages});
        })
    
      };
      
    render() {
        return (
          <Dropdown value={this.state.visualising} className={this.state.class} onChange={this.changeVisualising}>
            {this.state.languages}
          </Dropdown>
        );
    }
}
export default withTranslation()(SwitchLanguage);`
