### ISSUE TITLE
auto-close mobile menu on Navbar.Item click or location change

### ISSUE THREAD

**Issue by jdmg94** [couds/react-bulma-components#45]
the requested change is simple, pass toggleMenu to the Item elements in the render method of Navbar by adding the following lines.
```
if ([Item].includes(child.type)) {
    return React.cloneElement(child, { active: this.state.showMobileMenu, toggleMenu: this.toggleMenu });
}
```

then give us a boolean prop like `autoclose` or `closeable` on Navbar.Item which toggles the menu on the click event before its actual callback if any

**Comment by couds** [comment]
Actually I was thinking on removing this behavior, and make the navbar a controlled component (that receive the active prop).

**Comment by couds** [comment]
Hi @jdmg94 For the next major release (you can check the branch `next` this behavior will be removed and navbar will receive a new prop `active` which you can control. (see d4b62d0327d6d99b55e029dbc2f98662dbdbbf56)

**Comment by gregorskii** [comment]
This is working great, I don't quite know if the Storybook was enough to denote this feature.

Could use an explanation? Otherwise, I found this and it indeed works as expected.

Thanks!

**Comment by jdmg94** [comment]
@gregorskii when using react-router-dom the navigation is handled in browser, the navigation drawer stays open after following a link on the menu, this issue is going to be addressed in a future release by having this behavior handled by a prop that denotes the mobile drawer state.
