### ISSUE TITLE
Cannot Import Form Components

### ISSUE THREAD

**Issue by bramski** [couds/react-bulma-components#48]
Code:

```
import React from 'react';
import {Heading, Columns, Field} from 'react-bulma-components';

export default class CreateAccount extends React.Component {
  render() {
    return (
    <Columns>
      <Columns.Column className='has-text-centered'>
        <Heading>
          Create an Account
        </Heading>
        <Field></Field>
      </Columns.Column>
      <Columns.Column className="is-hidden-mobile has-text-centered">
        Right Stuff
      </Columns.Column>
    </Columns>);
  }
}
```

Error:
![screen shot 2018-06-21 at 2 42 56 pm](https://user-images.githubusercontent.com/421781/41747053-874cbcd6-7561-11e8-9563-b2aab149fe25.png)

Version:
1.4.6

**Comment by couds** [comment]
Hi @bramski.

The Field Component its not on the root of export, all the Form components are inside the Form Namespace, can you change the code to look like this? 

```
import React from 'react';
import {Heading, Columns, Form} from 'react-bulma-components';

export default class CreateAccount extends React.Component {
  render() {
    return (
    <Columns>
      <Columns.Column className='has-text-centered'>
        <Heading>
          Create an Account
        </Heading>
        <Form.Field></Form.Field>
      </Columns.Column>
      <Columns.Column className="is-hidden-mobile has-text-centered">
        Right Stuff
      </Columns.Column>
    </Columns>);
  }
}
```

Let me know if it works, 

Thanks

**Comment by capnrotbart** [comment]
I had exactly the same problem, your suggestion solved it for me. *Thanks!*

**Comment by rotexhawk** [comment]
I think importing components this way will significantly increase the bundle size as it will import everything. I am not sure if webpack's treeshaking can take care of that but at the least it will increase compile time during development.

**Comment by couds** [comment]
I recommend if possible to import each component like this 

`import Columns from 'react-bulma-components/lib/components/columns';` 

this will reduce the bundle size but you will need to add some configuration to your webpack as described on the Readme

**Comment by couds** [comment]
Closing this.
