### ISSUE TITLE
Add button `is-rounded` class (from Bulma)

### ISSUE THREAD

**Issue by koddr** [couds/react-bulma-components#52]
Hello @couds once more :)

Can you please add Bulma's `is-rounded` class to buttons?
It's feature since `0.6.2` version: https://bulma.io/documentation/elements/button/#styles

Thanks a lot!

**Comment by LaRuaNa** [comment]
Hi @koddr, instant fix on the way :)

**Comment by koddr** [comment]
Wow, guys! You're best 👍
