### ISSUE TITLE
How to use Button with Link from react-router-dom?

### ISSUE THREAD

**Issue by koddr** [couds/react-bulma-components#55]
Hello @couds and team :)

It's not allow in documentation, but still huge important thing — how to use `Button` component from `react-bulma-components` with `Link` from `react-router-dom`?

For example:

```jsx
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

import Columns from 'react-bulma-components/lib/components/columns';
import Heading from 'react-bulma-components/lib/components/heading';
import Button from 'react-bulma-components/lib/components/button';

class Navigation extends Component {
  render () {
    return (
      <Columns className="has-vertical-centered is-mobile" multiline>
        <Columns.Column>
          <div className="field is-grouped is-pulled-right">
            <p className="control">
              <Link to="/account">
                <Button color="white" className="is-rounded">
                  <span>My Account</span>
                </Button>
              </Link>
            </p>
          </div>
        </Columns.Column>
      </Columns>
    );
  }
}

export default Navigation;
```

And generated html code is:

```html
<div className="has-vertical-centered is-mobile columns is-multiline">
  <div className="column">
    <div className="field is-grouped is-pulled-right">
      <p className="control">
        <a href="/account">
          <a tabIndex="0" className="is-rounded is-white button">
            <span>My Account</span>
          </a>
        </a>
      </p>
  </div>
</div>
```

I mean one `<a>` tag into another `<a>` tag — it's strange and not valid. Okay, I can use `renderAs` props for `Button` to change tag to, for example, `<span>`. But if I do that, I get this error message in Chrome console:

```bash
Warning: Failed prop type: Invalid prop `renderAs` supplied to `Button`.
    in Button (at Navigation.js:19)
    in Navigation (at LandingIndex.js:12)
    in div (at LandingIndex.js:11)
    in div (at LandingIndex.js:10)
    in div (at LandingIndex.js:9)
    in LandingIndex (created by Route)
    in Route (at index.js:18)
    in Switch (at index.js:17)
    in Router (created by BrowserRouter)
    in BrowserRouter (at index.js:16)
```

How can I work via `react-router-dom` in right valid way? Please help ;)

P.S. and one more question.. what component may help me to replace this CSS classes to components: `field is-grouped` and its options, like `is-pulled-right` (or center/left)?

**Comment by LaRuaNa** [comment]
Hi @koddr, 
actually that should work that way. Maybe try to render as button. Honestly i dont understand the Warning at Navigation.js:19. There is no `renderAs ` prop and it should be as default `a`
Here an example of a project of mine:
```jsx
<Link to="/login">
  <Button renderAs="button">
    <span>Login</span>
  </Button>
</Link>

```

**Comment by LaRuaNa** [comment]
Im not sure if i understand you completely @koddr. Check the docs [here](https://couds.github.io/react-bulma-components/?selectedKind=Form&selectedStory=Default&full=0&addons=0&stories=1&panelRight=0). The Form componen might help you

**Comment by jdmg94** [comment]
@koddr you can pass the Link you imported from react-router-dom directly to the renderAs prop in the Button component, the props specific for the link will be passed over.

`<Button to="/somewhere" renderAs={Link}>My button linked to react-router-dom</Button>`

**Comment by koddr** [comment]
@jdmg94 OMG, it's great solution! Thanks.

Would be nice to push this info to `react-bulma-components` docs, btw.

**Comment by paustria** [comment]
I'm using this.
```
<Link to='/somewhere'>
    <Button>
          My button linked to react-router-dom
    </Button>
</Link>
```

**Comment by MrCreeper1008** [comment]
@koddr thank you for the issue. I'll put this in the new documentation :)

**Comment by dionart** [comment]
> I'm using this.
> 
> ```
> <Link to='/somewhere'>
>     <Button>
>           My button linked to react-router-dom
>     </Button>
> </Link>
> ```

have you found a way to take out the underline in the button?

**Comment by MrCreeper1008** [comment]
You can use the renderProp of `Button` and pass `Link` to it, and then either create a css class to remove the underline and pass the class name to the component via `className`, or create a `styled` component like:  
```
styled(Button)
```
and then remove the underline in the css.

**Comment by MrCreeper1008** [comment]
If it does not work please tell me.

**Comment by shasu01** [comment]
I am trying to link to another page **After** some process is completed on click of the button, but I cant get it _<Link to='/title'><Button  onClick={this.handleLoginClick}>My button</Button></Link>_

**Comment by jdmg94** [comment]
> I am trying to link to another page **After** some process is completed on click of the button, but I cant get it
> _ Link to='/title'>
> Button onClick={this.handleLoginClick}>My button
> /Link>_

ditch the `Link` component and access the [navigation history](https://reacttraining.com/react-router/web/api/Hooks/usehistory) directly, you can just add it to your click handler, i.e:

`<Button onClick={() => { handleLoginClick(); history.push('/title'); }}> My Button</Button>`

**Comment by jerome-diver** [comment]
@paustria 
if you do that:
> I'm using this.
> 
> ```
> <Link to='/somewhere'>
>     <Button>
>           My button linked to react-router-dom
>     </Button>
> </Link>
> ```

you have a button inside a (dirty).
the idea is to have a button contained the href to go.

**Comment by giorgiasatiani99** [comment]
k

**Comment by danielrb97** [comment]
heey idk if you fix the problem haha but i sue this:

<Link to='/somewhere'>
    <Button onClick={<Route></Route}></Button>
</Link>

**Comment by gugol2** [comment]
Well, semantically nesting an html button in an html a (or vice-versa) is not valid html...

https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fdropbox.beausmith.com%2Fstatic-html%2Finvalid-button-anchor-markup.html

So I would go for this approach: https://stackoverflow.com/questions/42463263/wrapping-a-react-router-link-in-an-html-button#answer-46088718

**Comment by MrCreeper1008** [comment]
There's `renderAs` prop for every component we export in `react-bulma-components`, so the best way to render `Link` as a `Button` is:
```jsx
<Button renderAs={Link} />
```

**Comment by chibie-code** [comment]
> > I am trying to link to another page **After** some process is completed on click of the button, but I cant get it
> > _ Link to='/title'>
> > Button onClick={this.handleLoginClick}>My button
> > /Link>_
> 
> ditch the `Link` component and access the [navigation history](https://reacttraining.com/react-router/web/api/Hooks/usehistory) directly, you can just add it to your click handler, i.e:
> 
> `<Button onClick={() => { handleLoginClick(); history.push('/title'); }}> My Button</Button>`

Thanks!

**Comment by premil** [comment]
<div className="create-btn">
                    <Link to="/newUser">
                        <Button
                            className='btn'
                            buttonStyle='btn-black-curve'
                            buttonSize='btn-medium'
                        >
                            Create
                        </Button>
                    </Link>
                </div>

I'm using this but didn't link to newUser page.. whats wrong with that?
