### ISSUE TITLE
Form example throws 'not defined' errors

### ISSUE THREAD

**Issue by arnaubt** [couds/react-bulma-components#57]
I was trying the example [here](https://couds.github.io/react-bulma-components/?selectedKind=Form&selectedStory=Default&full=0&addons=0&stories=1&panelRight=0) by importing the form component like that:

`import { Form } from 'react-bulma-components';`

But I'm getting a long list of errors from react:

```
Line 9:   'Field' is not defined       react/jsx-no-undef
Line 10:  'Label' is not defined       react/jsx-no-undef
Line 11:  'Control' is not defined     react/jsx-no-undef
...
```
Trying to import each component doesn't seem to be working either. Any idea what I'm missing?

**Comment by koddr** [comment]
Hi @arnaubt 

Usually, I get from `Form` component only what I want now (on current element of my React app).

Try to use import with decomposition:

```js
import { Field, Label, Control } from 'react-bulma-components/lib/components/form';
```

It good practice and save huge Kb of bundle.

**Comment by couds** [comment]
Hello, the Form components are inside the Form "namespace" to use them you import the Form Element and to use it you do `Form.Field` for the Field component and so on.

I hope this help you.

Let me know

**Comment by couds** [comment]
Hi @arnaubt For the next major release we will have a better documentation (the storybook will include the  code of the story that you could directly use) =)

You can follow the branch next to see the changes.

**Comment by arnaubt** [comment]
Many thanks for the responses! Waiting for that update.
