### ISSUE TITLE
Add Bulma's .is-mobile class

### ISSUE THREAD

**Issue by koddr** [couds/react-bulma-components#58]
Hello @couds and team.

I use this `.is-mobile` class for some UI elements, but don't see this into `react-bulma-components` :(
Can you please add this props?

This is official docs: https://bulma.io/documentation/columns/responsiveness/#mobile-columns

You make me happy every time I code via Bulma & React, btw 👍 
Thanks!

**Comment by jdmg94** [comment]
use the _breakpoint_ prop i.e:  `<Columns breakpoint="mobile" />`
