### ISSUE TITLE
[README] Make review for difference between RBC and React-Bulma package

### ISSUE THREAD

**Issue by koddr** [couds/react-bulma-components#60]
Hello @couds and team!

I research many React packages, who makes possible to use Bulma CSS Framework into React Components and found interesting thing: still alive and supported only two repos:

1. https://github.com/kulakowka/react-bulma (too awesome and older repo)
2. https://github.com/couds/react-bulma-components (our repo)

That's all. [Re-Bulma](https://github.com/bokuweb/re-bulma) is no longer maintained.

And question is: _What's difference between RBC and React-Bulma packages?_
Would be great to answer this question on our README for newbie people of Bulma+React 👍

**Comment by steph4nc** [comment]
There is also another react component library for Bulma: https://github.com/AlgusDark/bloomer it is built using TypeScript. I would also like a comparison overview of the different libraries.

**Comment by lnorton89** [comment]
So what's the consensus?

**Comment by couds** [comment]
I will close this.. does not seem that anyone would do this research.
