### ISSUE TITLE
Support TypeScript?

### ISSUE THREAD

**Issue by koddr** [couds/react-bulma-components#61]
Hello @couds and team.

TypeScript is here and covered React. 
I think, `react-bulma-components` need to add support of TS as soon as possible.

I'm not sure, but this is real "killer feature", because other React+Bulma repos doesn't have TS out of the box. We're may take this and get many stars and users for free!

I'm just learning TypeScript, but I see profit with this solution now.
Thanks!

**Comment by couds** [comment]
Hi @koddr I'm not a fan a TS but if the community want to add it I will not oppose.

What will be the benefits of adding TS? if we already have the Prop-types of the components?

**Comment by koddr** [comment]
@couds may I ask, what do you use? Flow?

Add TS support — it's about more support for tools, which community use right now and future. 

For example, I start new frontend project via `create-react-app --scripts-version=react-scripts-ts` and want to use `react-bulma-components` to it... yes, all works great, but if I want to write code with TypeScript — I need to components, like `MyComponent.tsx` (not `.jsx` or `.js`).

If I try to imports `react-bulma-components` in `.tsx` (or `.ts`) components, TS compiler show me error:

```
Try `npm install @types/react-bulma-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-bulma-components';`
```

And does not compile to JS.

**Comment by couds** [comment]
Hi @koddr I use plain JS, XD.

About TS, I you want can you create a .d.ts file with the declarations? (I will not change the library to ts but if I understood correctly we can add a .d.ts file with the type declarations, right?

**Comment by fibo** [comment]
@koddr if you are interested I am writing a set of React Bulma components using TypeScript https://github.com/fibo/trunx

**Comment by Acidic9** [comment]
+1 Would love to see typescript support

**Comment by voordev** [comment]
Shame there is no Solid Bulma implementation for react.
Shoudent this be something the Bulma foundation should take care of? 
An official react bundle

**Comment by MrCreeper1008** [comment]
If only I knew TS I would have submitted a PR. Not a fan of TS as well, but I wish someone could help.

**Comment by sc14aec** [comment]
Would also love to see Typescript support. I'm using this library for a project and intend to write type definitions as I go. If I make any significant progress I'll open a PR

**Comment by alagos** [comment]
Just as reference: 
Typescript support [was dropped](https://github.com/couds/react-bulma-components/pull/234) due to several issue and it will start to be rewritten [after 0.8.1 release](https://github.com/couds/react-bulma-components/issues/207#issuecomment-597810676).

**Comment by MrCreeper1008** [comment]
@alagos thank you for your clarification.
