### ISSUE TITLE
React Warning

### ISSUE THREAD

**Issue by gregorskii** [couds/react-bulma-components#65]
Hi,

I see this line is causing an error in newer versions of react:

https://github.com/couds/react-bulma-components/blob/master/src/components/navbar/navbar.js#L71

It is listed with a TODO to update.

Is there a plan to make this compat with the new React API?

Thanks!

**Comment by couds** [comment]
Hi.

This is already fixed on the version 2.0 (that it's currently marked as @next that will be soon released) 

If you want to try it you can install it with `npm install react-bulma-components@next` 

This version have a few breaking changes and I'm still working on it. I'm planning to release it the next month will a migration steps document.

Thanks
