### ISSUE TITLE
Component documentation

### ISSUE THREAD

**Issue by TMiguelT** [couds/react-bulma-components#68]
Hi, I found it very confusing as a new user of the library, because many of the components are namespaced but not others.

For example, to access the `Button` component, you can import it directly

```javascript
import { Button } from 'react-bulma-components/full'

<Button>
```

But to access the `Input` component, you need to go into the Form object:

```javascript
import { Form } from 'react-bulma-components/full'

<Form.Input/>
```

However this isn't documented anywhere! Am I missing something obvious here?

**Comment by couds** [comment]
Hi @TMiguelT  Thanks for using this library

-sorry about the documentation, right now the only real documentation are the storybbok. but the current version storybook its not good enough, Im working on the v2.0.0 (right now you can start using the prerelease version with `npm i  react-bulma-components@next`) to improve the storybook to add the correct code examples like this.

![image](https://user-images.githubusercontent.com/2903371/43649297-13f91d26-973d-11e8-8b06-fa8c9d643efa.png)

I'm doing some testing I trying to release this version maybe the next week.

Thanks!

**Comment by TMiguelT** [comment]
Ah great, if the storybook includes code examples it would be very helpful!

**Comment by couds** [comment]
Hi @TMiguelT I just release the v2 of the library. I hope that with the new storybook the library will be easier to use. 

PD. I'm closing this issue, if you have any issue do not hesitate to open a new issue =)
