### ISSUE TITLE
Forms won't import at the root

### ISSUE THREAD

**Issue by cereallarceny** [couds/react-bulma-components#76]
I'm forced to import the `Field`, `Control`, and `Input` (and likely other modules) at `react-bulma-components/lib/components/form` rather than at `react-bulma-components`.

**This works:**
```es6
import {
  Columns,
  Heading,
  Box,
  Container,
  Section,
  Button,
  Level,
  Card,
  Media,
  Image,
  Content,
  Tag,
  Message,
  Hero
} from 'react-bulma-components';

import {
  Field,
  Control,
  Input
} from 'react-bulma-components/lib/components/form';
```

**This does not work:**
```es6
import {
  Columns,
  Heading,
  Box,
  Container,
  Section,
  Button,
  Level,
  Card,
  Media,
  Image,
  Content,
  Tag,
  Message,
  Hero,
  Field,
  Control,
  Input
} from 'react-bulma-components';
```

**Comment by couds** [comment]
Hi @cereallarceny all the form components are inside the Form component,

you can do this

```
import { Form } from 'react-bulma-components';

const { Input, Field, Control } = Form;
```

Also I think I this this should work (didn't tested yet)

```
import { Form: { Input, Control } } from 'react-bulma-components'
```

**Comment by cereallarceny** [comment]
Oh wow, that's awesome.  Is there any reason that shouldn't just import directly from the root package like all the other elements?

Also, I'd love to help with documentation on this project.  It seems like there's a lot of props that either aren't in the Storybook or that I've found by accident in reading the source code.  Do you have any timeline, issues, or roadmap associated with this?  Of course, the storybook and Bulma docs are helpful, but the classes don't always match up perfectly with the React props, so there's sometimes some ambiguity in how they should be spelled.

Any pointers in the right direction?  It would be great to not have to read the source code to see what props are available for specific elements.

**Comment by couds** [comment]
Yes the idea it to not overpopulate the root namespace, normally you will use the form components together so make sense to group then all.

Right now My hands are full with other projects I do not have a timeline for improve the docs, but mostly all props are showed on each component storybook, with the exception of the common props that are only on the `Element` component.

If you can contribute improving the docs that will be a huge help.

Thanks

**Comment by couds** [comment]
Closing this due inactivity

**Comment by verheyenkoen** [comment]
I struggled with this too until I found this ticket. I guess it would be good to note this in the README or in the storybook somehow.
