### ISSUE TITLE
All components should support `renderAs` prop

### ISSUE THREAD

**Issue by RickEyre** [couds/react-bulma-components#81]
This would be super useful and make the library much more flexible.

Thoughts?

**Comment by couds** [comment]
Hi @RickEyre All components support the prop RenderAs. If not that was by mistake. Did you found a component without the renderAs prop?

**Comment by RickEyre** [comment]
I was trying on Columns today and it was not. In the code it looks like it's hard-coded to div.

**Comment by couds** [comment]
Thanks Rick you are right. That was a mistake should have the renderAs prop. The next version will have that fixed

**Comment by RickEyre** [comment]
Thanks!
