### ISSUE TITLE
[Navbar Navbar.Burger] Uncaught TypeError: Cannot read property 'setState' of undefined

### ISSUE THREAD

**Issue by dextel2** [couds/react-bulma-components#84]
So while learning examples on Storybook I came across this error and I cannot figure it out how it is caused. Can someone provide an ES6 solution to it?
![issue](https://user-images.githubusercontent.com/16697307/46031179-c944bf80-c115-11e8-9376-ce634e0211c5.png)

**Comment by dextel2** [comment]
Solved it, Here is the entire code

`import React, { Component } from "react";
import { Navbar } from "react-bulma-components/full";
class MenuNavbar extends Component {
  render() {
    return (
      <div id="header">
        <Navbar color="info" fixed="top">
          <Navbar.Brand>
            <Navbar.Item renderAs="a" href="/">
              <img src="https://i.imgur.com/9jQaBuq.png" alt="Dew Ventures" />
            </Navbar.Item>
            <Navbar.Burger />
          </Navbar.Brand>
          <Navbar.Menu>
            <Navbar.Container>
              <Navbar.Item href="/">Home</Navbar.Item>
              <Navbar.Item href="/about"> About Us</Navbar.Item>
              <Navbar.Item href="/contact"> Contact Us</Navbar.Item>
            </Navbar.Container>
          </Navbar.Menu>
        </Navbar>
      </div>
    );
  }
}

export default MenuNavbar;`

**Comment by moskalyk** [comment]
Does your navbar dropdown work when you resize the page? @dextel2
