### ISSUE TITLE
Dropdown behaviour of showcase can not be reproduced

### ISSUE THREAD

**Issue by jonalv** [couds/react-bulma-components#85]
Let me start by saying I am sorry if I am cross posting I just realised that I am having more trouble in my example at https://github.com/jonalv/bulma-react-example than just only the icon not showing up and thus this should probably be a ticket of it's own...

I am trying to follow the instructions at: https://couds.github.io/react-bulma-components/?selectedKind=Dropdown&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

I don't get the little triangle pointing down on the Dropdown menu but the behaviour of the Dropdown is not correct either since the hover effect on the dropdown is not showing a pointer hand (as on links) thingie (if you know what I mean?:). Either something is broken or I am doing something wrong and then maybe the instructions could be extended?

**Comment by couds** [comment]
@jdmg94 Sorry for the delay, can you provide me an example repo to reproduce this issue?

Thanks

**Comment by jonalv** [comment]
Yea: https://github.com/jonalv/bulma-react-example

**Comment by weyert** [comment]
Yes, I am experiencing the same issue within my own code. I am having the feeling some of the dropdown related css code is missing which causes this issue. As looks missing in the CSS that CRA/app is injecting in the html page

**Comment by jonalv** [comment]
Yes that seems to have worked.
