### ISSUE TITLE
Failed prop type: Invalid prop `renderAs` supplied to `d`.     in d (at DashboardLayout.js:43)

### ISSUE THREAD

**Issue by weyert** [couds/react-bulma-components#87]
I am trying to use the `renderAs`-property on the `NavBar.Item`-component so it uses the @reach/router's `Link`-component but it looks like `renderAs`-proeprty doesn't accept the component as input e.g.

```<NavBar.Item to="/dashboard" renderAs={Link}>NavItem</NavBar.Item>```

I also tried it with Button but getting a similar error: ```Warning: Failed prop type: Invalid prop `renderAs` supplied to `c`.
    in c (at DashboardLayout.js:42)```

using the code snippet:
```<Button to="/dashboard" renderAs={Link}>NavItem</Button>```

**Comment by MrCreeper1008** [comment]
I used it with React Router's Link component and it works just fine. The only difference is that I have the Link component wrapped as a styled component, but that shouldnt affect anything.

**Comment by weyert** [comment]
I ended up not using `Bulma`-component but use the Bulma classes for now:

```
export const NavLink = props => (
    <Link
      getProps={({ isPartiallyCurrent }) => ({
        className: isPartiallyCurrent ? "navbar-item is-active" : "navbar-item"
      })}
      {...props}
    />
);
```

**Comment by MrCreeper1008** [comment]
I use named import from `react-bulma-components` and it works just fine.
`import { NavBar } from 'react-bulma-components';`

**Comment by couds** [comment]
@weyert this is still an issue?

**Comment by weyert** [comment]
I have decided I will just keep using the working solution as given above for now :) 
Thanks again for your help!
