### ISSUE TITLE
Filter DOM properties before rendering element

### ISSUE THREAD

**Issue by RickEyre** [couds/react-bulma-components#89]
I have a lot of warnings and errors in my console due to bulma components passing through properties to DOM elements that are not DOM properties.

Using something like [pick react known prop](https://www.npmjs.com/package/pick-react-known-prop) to filter the properties may be useful.

**Comment by couds** [comment]
Hi @RickEyre can you give me an example of which component is giving you the warnings?

I dont think I will implement the filter because this will be in conflict with the renderAs prop.

**Comment by MrCreeper1008** [comment]
Hi, here is an example:
![Example](https://user-images.githubusercontent.com/19359984/46672500-2f4b3f80-cc0a-11e8-8d13-f12afda7b7fb.png)  
The `isediting` prop in `<h1>` slipped into the actual DOM, which is a custom prop I add in conjunction with styled-components to create dynamic styles.  

And here is the warning:
![Warning](https://user-images.githubusercontent.com/19359984/46672655-949f3080-cc0a-11e8-8718-2baf6996d01c.png)

**Comment by MrCreeper1008** [comment]
Note that I did not use the `renderAs` prop here.

**Comment by couds** [comment]
Hi @MrCreeper1008 I don't think this case should be handled by this library. you code is passing an invalid prop to the component with or without the Bulma Component. but just to check can you share the code you use  that cause the error?

**Comment by RickEyre** [comment]
I think it's relatively common in these types of libraries to filter out props before you render the final element. Due to the nature of pass through props as a coding convention in React nowadays it's necessary IMO. 

A simple solution would be to check whether or not what you are about to render is an HTML element, i.e. typeof renderAs === 'string', and if so, filter out the properties. If it's not a string then it means it's a custom Component and you should pass through the props.

I used a similar method in a design system I built recently.

You can generalize that logic into a HOC or a component that does the render to help.

**Comment by RickEyre** [comment]
Thanks for providing a nexample @MrCreeper1008.

**Comment by couds** [comment]
Hi @RickEyre  @MrCreeper1008 After doing some research I will not add this validation logic to the library, the developer or the external libraries should no pass down the non-html attributes, for the same reason React stopped filtering on v16. https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

IMO this filter it trying to hide an error in other part of the code.

**Comment by MrCreeper1008** [comment]
So is it not possible to use the components of this libraries with styled-components? Adding custom props to components is fairly common in styled-components to achieve dynamic styles.

**Comment by couds** [comment]
It is possible, but the question here is "who is responsible of avoiding this props to be passed down?" I don't think this library because the only one that know if a prop should be passed down its the developer, I dont know if someone using the library need other props on the DOM because of some legacy code or other reasons. If you want you can wrap and the bulma components on another component or create an HoC to clean the props before passing them to the bulma components for example.

I want to keep this library aas simple as possible and one one responsibility "wrap Bulma styles on React components".

**Comment by MrCreeper1008** [comment]
Makes sense. Thank you!

**Comment by RickEyre** [comment]
Okaaaay. I'll do it myself... thanks @couds

**Comment by couds** [comment]
To finalize this issue you can follow the thread https://github.com/styled-components/styled-components/issues/439.
