### ISSUE TITLE
Support .buttons class (list of buttons)

### ISSUE THREAD

**Issue by MrCreeper1008** [couds/react-bulma-components#93]
Doc for `.buttons` class: https://bulma.io/documentation/elements/button/#list-of-buttons  
The class groups buttons as a **list** and will **automatically wrap on multiple lines** when needed.  

Example:  
```
<Buttons>
  <Button
    renderAs="span"
    color="success">
    Save changes
  </Button>
  <Button
    renderAs="span"
    color="info">
    Save and continue
  </Button>
  <Button
    renderAs="span"
    color="danger">
    Cancel
  </Button>
<Buttons>
```  
Any thoughts? I can make a pull request on it.

**Comment by MrCreeper1008** [comment]
`<Buttons />` could have two props, `addons` and `position`, corresponding to the two modifier class, i.e. `has-addons`, `is-centered`, and `is-right`.  
```
{
  addons: PropTypes.bool,
  position: PropTypes.oneOf(['center', 'right])
}
```  
A new prop, `selected`, could be added to `<Button />`, corresponding to the modifier class `is-selected`.  
```
{ selected: PropTypes.bool }
```

**Comment by couds** [comment]
I was thinking on adding that component. If you can do a PR that would be great! Thanks

**Comment by MrCreeper1008** [comment]
Will do in my free time. No problem!

**Comment by MrCreeper1008** [comment]
@couds Should I categorize <Buttons /> under Button in storybook?

**Comment by couds** [comment]
Sure!

**Comment by MrCreeper1008** [comment]
Hi @couds, I think it would be better to put `<Buttons />` in the same level as `<Button />` in storybook.
Like
```
|_Button
|_Buttons
```
rather than
```
|_Button
   |_Default
   |_...
   |_Buttons
```
How do you think?
