### ISSUE TITLE
Icon-component: Semicolons aren't allowed in the indented syntax

### ISSUE THREAD

**Issue by codekie** [couds/react-bulma-components#94]
`dart-sass` won't allow processing the `icon.sass`, due to the semicolon at the end of this line:

https://github.com/couds/react-bulma-components/blob/71e6902c7d2bf8b7e47df4b8ad5ee66b1cdf40e4/src/components/icon/icon.sass#L6

**Comment by couds** [comment]
Hi @codekie Thank for reporting this. I will release this after merging  #95

**Comment by codekie** [comment]
Hi @couds are there any plans when `2.1.1` will be released?

**Comment by couds** [comment]
Hi @codekie Yes I had a craxy few weeks. I will try to do it tomorrow or this weekend. sorry for the delay!

**Comment by codekie** [comment]
Great, thank you! Keep up the good work! 🙂👍
