### ISSUE TITLE
Broken in CRA 2.0.4

### ISSUE THREAD

**Issue by cereallarceny** [couds/react-bulma-components#96]
When upgrading to `react-scripts@2.0.4`, I receive the following error:

```
Failed to compile.

./node_modules/react-bulma-components/lib/components/columns/columns.sass (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./node_modules/react-bulma-components/lib/components/columns/columns.sass)
@import "~_variables.sass"
^
      File to import not found or unreadable: ~_variables.sass.
      in /Users/cereallarceny/Dropbox/Development/openmined/code/syft-autocomplete-example/node_modules/react-bulma-components/lib/components/utils.sass (line 3, column 1)
```

My currently SASS implementation is done as such:
```sass
@import url('https://fonts.googleapis.com/css?family=Overpass:400,400i,700,700i,900,900i');

$family-sans-serif: 'Overpass', sans-serif;

@import '~react-bulma-components/src/index';
```

The problem is that SASS is automatically compiled in CRA 2.0+ now via the `node-sass` package, not the one mentioned in your documentation.  You no longer need to compile it like mentioned in your readme.  The fix is simple: change the line in `utils.sass` to read `@import "_variables.sass"` - without the tilde (~).  I'll be submitting a PR for this momentarily.

**Comment by dextel2** [comment]
Hi, unless until the commit is merged, I'd suggest to manually change from `@import "~_variables.sass"` to `@import "_variables.sass"` , in `utils.sass`
