### ISSUE TITLE
Allow the use of `ref` in the button component

### ISSUE THREAD

**Issue by weyert** [couds/react-bulma-components#98]
I am trying to use the `Button`-component together with the Reach UI library's `AlertDialog` and it's causing some trouble because you can't use `ref` with the `Button`-component. The React documentation suggests that `forwardRef` can be used to allow this, see:
https://reactjs.org/docs/forwarding-refs.html

Potentially, this would also avoid change the `Input` etc to class components at the same time 

`react-bulma-components` version in use is: 2.1.0

**Comment by couds** [comment]
Hi @weyert thanks I didn't know about the forwarding-refs. That make sense. I will try to fix some time to do it, but if someone want to do a PR its more than welcome =).

@MrCreeper1008 What @weyert  is saying its that using the forwarding-refs we can revert this change d4c9374f4f26e1d0cb1bc235875e3a5ca5a3d407 (change Input component from a functional component to a class component)

**Comment by MrCreeper1008** [comment]
OK cool, sorry for the misunderstanding.  
So should all components support ref forwarding for consistency, or just `<Button />`?

**Comment by MrCreeper1008** [comment]
According to the React doc supporting ref forwarding would require a major version change. Probably a good idea to combine this change and https://github.com/couds/react-bulma-components/pull/97?

**Comment by weyert** [comment]
I think we could consider to add it to all components or otherwise who could potentially focus?

**Comment by MrCreeper1008** [comment]
Yea makes sense, I'll probably submit a PR for it during my free time.

**Comment by MrCreeper1008** [comment]
Ref forwarding is achieved in my local fork, but if I get it right, the component supplied in the `renderAs` should forward ref appropriately as well.

**Comment by MrCreeper1008** [comment]
@couds I think we should create a check list that keeps track of components that support ref forwarding. How do you think?

**Comment by MrCreeper1008** [comment]
Ref forwarding is a breaking change. Should gradually add support for ref forwarding for each components instead of doing it all at once in a commit.

**Comment by couds** [comment]
Hi @MrCreeper1008 I think it should be a one PR, and as you suggest ship it with #97

**Comment by MrCreeper1008** [comment]
OK sure

**Comment by weyert** [comment]
Wow great, I will give it a shot! Where can I find your code changes, @MrCreeper1008?

**Comment by MrCreeper1008** [comment]
It's still on my local repo, will push to my fork after passing tests.

**Comment by MrCreeper1008** [comment]
@couds Enzyme 3.3.0 is having issue with forwardRef, fix is on 3.5.0. Upgrade?

**Comment by couds** [comment]
no problem if do not cause anything else to break.

**Comment by MrCreeper1008** [comment]
@couds even after upgrading to 3.5.0, I'm still having issue with forwardRef in Enzyme as described here: https://github.com/airbnb/enzyme/issues/1604. Need a bit more time...

**Comment by MrCreeper1008** [comment]
OK after hours of fighting with Enzyme...i still can't figure out how to test component wrapped with `forwardRef`.....

**Comment by MrCreeper1008** [comment]
@couds sorry I am quite busy recently. I already implemented ref forwarding, but I'm stuck at testing. I'll submit a pr tomorrow.

**Comment by weyert** [comment]
Thanks for your work @MrCreeper1008. Let's have a look at it tomorrow
