### ISSUE TITLE
Table does not have renderAs prop

### ISSUE THREAD

**Issue by CodeDraken** [couds/react-bulma-components#99]
@couds mentioned all components should have a renderAs prop. #81

**Comment by CodeDraken** [comment]
Alright, it's worth noting that other major UI libraries ( such as [Semantic UI](https://github.com/Semantic-Org/Semantic-UI-React) ) do support custom elements for everything.

For example:
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/collections/Table/Table.js

**Comment by couds** [comment]
Hi. Can you give me an example why do you need this? Just doing it because other library does it's not enough reason (at least to me).

Thanks

**Comment by couds** [comment]
Closing this due inactivity. Please reopen it if you think its necessary.
